// src/lib/registry/items.ts
// 如月公寓物品注册表 - 60件，每件有唯一主人(NPC/诡异)，无评级，有来历/副作用/价值
// 仅5件可路上拾取(主人遗漏)，其余仅通过：交易/击杀/高好感赠予/任务获得

import type { Item } from "./types";

export const ITEMS: readonly Item[] = [
  // ===== 可路上拾取 5 件（主人遗漏，概率极低）=====
  {
    id: "I-001",
    name: "陈婆婆的毛线团",
    ownerId: "N-001",
    description: "一团未织完的毛线，颜色诡异渐变。可短暂缠绕小型诡异。",
    origin: "陈婆婆在3楼看阿花时遗落。毛线来自她织给逝者的毛衣，每根线都缠着公寓消化前的记忆。",
    sideEffect: "使用后毛线会「长」入指尖，24小时内需用剪刀切断，否则指尖坏死。",
    value: "缠绕诡异3秒；赠予织造相关NPC可大幅增加好感。",
    canFindOnRoad: true,
    statRequirement: { charm: 3 },
    statBonus: { charm: 1 },
    tags: "binding,favor",
  },
  {
    id: "I-002",
    name: "林医生的听诊器",
    ownerId: "N-002",
    description: "能听见墙壁内部「消化」声的听诊器。可预判器官拟态墙出现位置。",
    origin: "林医生去4楼探视盲人时遗落在走廊。曾用来听诊七名死者的最后心跳，那些心跳已刻进金属膜片。",
    sideEffect: "长时间佩戴会听见自己的心跳逐渐变慢，易诱发恐慌。",
    value: "预判拟态墙；赠还林医生可增加好感。",
    canFindOnRoad: true,
    statRequirement: { background: 4 },
    statBonus: { background: 2 },
    tags: "diagnostic,favor",
  },
  {
    id: "I-003",
    name: "邮差的空白信封",
    ownerId: "N-003",
    description: "没有寄件人也没有收件人的信封。将名字写在信封上可短暂屏蔽其与13楼门扉的因果。",
    origin: "邮差老王塞错信箱时遗落。这封信本该寄给「下一个被消化的人」，收件人栏会随时间自动填满。",
    sideEffect: "使用后信封会自动填满讣告内容，阅读者理智-5。",
    value: "屏蔽13楼因果一次；赠予邮差可增加好感。",
    canFindOnRoad: true,
    statRequirement: { luck: 5 },
    statBonus: { luck: 2 },
    tags: "mail,consumable",
  },
  {
    id: "I-004",
    name: "沾染腥味的狗绳",
    ownerId: "N-005",
    description: "褪色皮质狗绳，末端断裂，沾满暗色污渍。曾属于盲人的导盲犬大黄。",
    origin: "大黄被无头猎犬吞噬后，盲人在4楼走廊捡到残骸旁的断绳。他至今不知道真相。",
    sideEffect: "携带会吸引无头猎犬的注意，但在4楼可使其短暂困惑数秒。",
    value: "无头猎犬困惑3秒，争取逃生时间；归还盲人可大幅增加好感。",
    canFindOnRoad: true,
    statRequirement: { agility: 4 },
    statBonus: { agility: 2 },
    tags: "beast,memory",
  },
  {
    id: "I-005",
    name: "皱巴巴的报纸",
    ownerId: "N-006",
    description: "日期模糊的旧报纸。可包裹其他物品隔绝气息。",
    origin: "张先生门口椅子上落下。他从不看日期，报纸上的新闻会在无人注视时更新成与持有者相关的噩耗。",
    sideEffect: "包裹物后，报纸会逐渐显现持有者的死因预告。",
    value: "隔绝物品气息；赠予张先生可增加好感。",
    canFindOnRoad: true,
    statRequirement: { sanity: 3 },
    tags: "wrapper,ominous",
  },
  // ===== N-001 陈婆婆 2件 =====
  {
    id: "I-006",
    name: "陈婆婆的织针",
    ownerId: "N-001",
    description: "金属织针，针尖泛冷光。归还或赠予织造相关住客可换取重大恩情。",
    origin: "陈婆婆织了无数件毛衣，每件对应一个被她遗忘的人。这根针穿过所有那些未完成的告别。",
    sideEffect: "持有时会偶尔听见织针划过毛线的沙沙声，来自不存在的房间。",
    value: "赠予织造相关NPC大幅增加好感；可换取庇护或情报。",
    statRequirement: { charm: 6 },
    statBonus: { charm: 2 },
    tags: "gift,favor",
  },
  {
    id: "I-007",
    name: "褪色的碎花布",
    ownerId: "N-001",
    description: "陈婆婆衣裳上扯下的碎布。带有她的气息。",
    origin: "她某次从3楼慌张返回时勾破的。阿花差点被认知腐蚀者盯上，她用身体挡了一下。",
    sideEffect: "携带时认知腐蚀者的定位会延迟，但陈婆婆会感知到布的位置。",
    value: "延缓认知腐蚀；赠还陈婆婆可增加好感。",
    statRequirement: { sanity: 5 },
    statBonus: { sanity: 1 },
    tags: "memory,favor",
  },
  // ===== N-002 林医生 2件 =====
  {
    id: "I-008",
    name: "林医生的处方笺",
    ownerId: "N-002",
    description: "空白处方笺，印有林医生签名。写下NPC名字并「开药」可增加其好感。",
    origin: "她从三甲医院带出的最后一批处方笺。七名患者的死因被写在这些纸上，然后被她撕掉。",
    sideEffect: "仅限使用一次；使用后诊室会传来七声叹息。",
    value: "增加目标NPC好感；对方会认为你懂医术。",
    statRequirement: { charm: 7 },
    statBonus: { charm: 2 },
    tags: "gift,favor",
  },
  {
    id: "I-009",
    name: "安神剂空瓶",
    ownerId: "N-002",
    description: "诊室甜腻气味的来源。瓶底残留粘稠液体。",
    origin: "林医生用管道沉淀物自制的安神剂。她靠这个维持「医生」的幻觉，原料来自公寓消化系统。",
    sideEffect: "饮用残留液可暂时屏蔽腐臭，但会成瘾，停用后理智-10。",
    value: "屏蔽嗅觉30分钟；可用来与林医生交易。",
    statRequirement: { sanity: 4 },
    tags: "chemical,risky",
  },
  // ===== N-003 邮差 2件 =====
  {
    id: "I-010",
    name: "邮差的挂号信",
    ownerId: "N-003",
    description: "未投递的挂号信，收件人处空白。填入NPC名字并「送达」可大幅增加其好感。",
    origin: "邮差派送路线中永远无法送达的一单。收件人已死，信的内容是死者的遗言。",
    sideEffect: "送达后，寄件人会「记得」你，可能在未来某夜敲你的门。",
    value: "强制完成邮差因果，大幅增加目标NPC好感。",
    statRequirement: { luck: 7 },
    statBonus: { luck: 2 },
    tags: "gift,favor",
  },
  {
    id: "I-011",
    name: "褪色明信片",
    ownerId: "N-003",
    description: "没有邮戳的明信片，背面写着「别回来」。",
    origin: "某住户逃离公寓前寄给自己的警告。信从未寄出，一直躺在邮差包里。",
    sideEffect: "可临时阻挡邮差视线使其跳过你一次；一小时后明信片自动消失。",
    value: "躲避邮差一次投递。",
    statRequirement: { luck: 4 },
    tags: "mail,consumable",
  },
  // ===== N-004 阿花 2件 =====
  {
    id: "I-012",
    name: "阿花的黑色毽子",
    ownerId: "N-004",
    description: "黑色毽子，落地声像骨头敲击。据说是用「不乖的孩子」的头发扎成。",
    origin: "阿花等妈妈下班时唯一的玩伴。她不知道妈妈永远不会回来了，毽子记得每一个陪她玩过的孩子。",
    sideEffect: "踢动会吸引楼梯间倒行者的注意；但可用来与阿花做交易。",
    value: "与阿花交易；制造声响诱饵（风险自负）。",
    statRequirement: { charm: 4 },
    tags: "bait,memory",
  },
  {
    id: "I-013",
    name: "断开的红绳手链",
    ownerId: "N-004",
    description: "儿童尺寸的红绳，已断开。曾用于辟邪。",
    origin: "阿花妈妈给女儿戴上的。断裂的那晚，妈妈没有回家。阿花一直带在身上。",
    sideEffect: "可短暂延缓认知腐蚀者定位；佩戴超过1小时会梦见一个穿红裙的女人在找孩子。",
    value: "延缓认知污染；赠还阿花可增加好感。",
    statRequirement: { sanity: 5 },
    statBonus: { sanity: 0 },
    tags: "charm,weak",
  },
  // ===== N-005 盲人 1件 =====
  {
    id: "I-014",
    name: "白色盲杖",
    ownerId: "N-005",
    description: "标准白色盲杖。盲人唯一的行动依赖。",
    origin: "大黄走失后他唯一的「眼睛」。杖尖敲过的地面会短暂保留他的足迹，无头猎犬能追踪。",
    sideEffect: "使用会留下可追踪足迹；但在4楼敲击可制造诱饵声源。",
    value: "制造声源诱饵；归还盲人可大幅增加好感并获得情报。",
    statRequirement: { agility: 4 },
    statBonus: { agility: 1 },
    tags: "tool,favor",
  },
  // ===== N-006 张先生 2件 =====
  {
    id: "I-015",
    name: "停止转动的怀表",
    ownerId: "N-006",
    description: "秒针永久停在2:47的怀表。持有者偶尔听见表内倒计时的滴答声。",
    origin: "张先生退休时学生送的。他不再看日期后，表也停了。时间在2:47那刻凝固——那是他最后一堂课的结束铃。",
    sideEffect: "聆听滴答声可短暂篡改局部时间流速，但会加剧时差症候群的侵袭。",
    value: "短暂改变局部时间；可抵抗时差症候群因果侵蚀。",
    statRequirement: { luck: 10, background: 8 },
    statBonus: { luck: 3, sanity: 2 },
    tags: "time,rewind",
  },
  {
    id: "I-016",
    name: "无日期老花镜",
    ownerId: "N-006",
    description: "镜片有细微裂纹。戴上可看清扭曲文字的真实含义。",
    origin: "张先生用来看报纸的。他故意选了没有刻度的款式，这样就不会看见日期。",
    sideEffect: "佩戴超过10分钟会开始看见未来的片段，理智-3。",
    value: "解读认知腐蚀者扭曲的文字；抵挡一次轻度精神污染。",
    statRequirement: { sanity: 6 },
    statBonus: { sanity: 2 },
    tags: "vision,consumable",
  },
  // ===== N-007 画家 2件 =====
  {
    id: "I-017",
    name: "金属书签",
    ownerId: "N-007",
    description: "刻着无法辨认页码的金属书签。夹入书本可临时遮蔽存在。",
    origin: "画家从夜读老人那里偷来的。她本想夹进自画像里「藏住」自己，但书签会逐渐显现使用者的名字。",
    sideEffect: "使用后书签会显现你的名字，认知腐蚀者可据此定位。",
    value: "遮蔽存在，使认知腐蚀者难以定位；赠予夜读老人可增加好感。",
    statRequirement: { sanity: 5 },
    statBonus: { sanity: 1 },
    tags: "conceal,cognition",
  },
  {
    id: "I-018",
    name: "颜料调色盘",
    ownerId: "N-007",
    description: "沾满未干颜料的调色盘。颜色从未重复。",
    origin: "画家寻找「真实的脸」时用的。每幅自画像的眼睛位置都错了，颜料记得那些错误的尝试。",
    sideEffect: "触碰颜料会短暂看见画家眼中的世界——无数张脸重叠，理智-2。",
    value: "可用来与画家交易；涂抹在门缝可隔绝气息。",
    statRequirement: { charm: 4 },
    tags: "trade,utility",
  },
  // ===== N-008 电工 2件 =====
  {
    id: "I-019",
    name: "万能螺丝刀",
    ownerId: "N-008",
    description: "电工老刘的螺丝刀。可拆卸公寓内大部分设备。",
    origin: "他修电路时用的。某次检修他看见墙壁内部的「布线」——不是电线，是血管。他再也没问线从哪来。",
    sideEffect: "拆卸错误的「电路」会引发短路，可能惊动整层诡异。",
    value: "拆卸设备；可用来与电工交易；赠还可增加好感。",
    statRequirement: { agility: 5 },
    statBonus: { agility: 1 },
    tags: "tool,favor",
  },
  {
    id: "I-020",
    name: "备用电池",
    ownerId: "N-008",
    description: "物业配发的5号电池一对。可恢复手电或机械表续航。",
    origin: "电工从配电间「抢救」出来的。电池本身不带污染，是公寓里少数干净的东西。",
    sideEffect: "无。",
    value: "恢复设备续航。",
    statRequirement: { background: 3 },
    tags: "utility,clean",
  },
  // ===== N-009 双胞胎 2件 =====
  {
    id: "I-021",
    name: "共鸣水晶",
    ownerId: "N-009",
    description: "一对相连的水晶。靠近时会共振。",
    origin: "双胞胎姐妹共用一颗心脏的物理证明。水晶共振时，两人能共享知觉。",
    sideEffect: "持有一块时，另一块在谁手上你会逐渐感知到——反之亦然。",
    value: "与双胞胎交易；可用来「分裂」某些诡异的注意力。",
    statRequirement: { charm: 6 },
    statBonus: { charm: 2 },
    tags: "trade,favor",
  },
  {
    id: "I-022",
    name: "白色发卡",
    ownerId: "N-009",
    description: "普通的白色发卡。双胞胎各有一只。",
    origin: "她们「变成两个」之前唯一拥有的东西。现在每人一只，弄丢的人会慢慢消失。",
    sideEffect: "携带发卡超过24小时，你会开始听见另一个人的心跳。",
    value: "赠还双胞胎可增加好感；可用来证明「你选择了其中一个」。",
    statRequirement: { charm: 5 },
    tags: "memory,favor",
  },
  // ===== N-010 物业经理 2件 =====
  {
    id: "I-023",
    name: "物业印章",
    ownerId: "N-010",
    description: "物业办公室的正式印章。可伪造部分文件。",
    origin: "工牌背面刻着「消化完成前，请勿离开」。印章盖下的每个批注都是消化进度的一部分。",
    sideEffect: "使用伪造文件会被物业列入「优先消化」名单。",
    value: "糊弄一次物业流程；赠予对物业有敌意的NPC可增加好感。",
    statRequirement: { background: 8, charm: 6 },
    statBonus: { background: 2 },
    tags: "intel,risky",
  },
  {
    id: "I-024",
    name: "保安巡逻表",
    ownerId: "N-010",
    description: "物业保安的巡逻时间表。可精准规避巡逻路线。",
    origin: "物业经理桌上漏出来的副本。他知道谁在看，但他不在乎——消化会追上所有人。",
    sideEffect: "表上的时间有时会错，因为保安的路线会随消化进度调整。",
    value: "规避巡逻；赠予对物业有敌意的NPC可增加好感并换取合作。",
    statRequirement: { agility: 5, background: 4 },
    statBonus: { agility: 2, background: 1 },
    tags: "intel,favor",
  },
  // ===== N-011 夜读老人 2件 =====
  {
    id: "I-025",
    name: "消化日志残页",
    ownerId: "N-011",
    description: "夜读老人手中厚书的脱落页。记载公寓消化进度。",
    origin: "他读的是公寓的消化日志，每页一个被吸收的住户。残页脱落意味着某人即将被消化。",
    sideEffect: "阅读会看见自己的名字出现在某页，页码即死期。理智-5。",
    value: "知晓公寓真相；可利用规则漏洞对诡异施加规则类杀伤。",
    statRequirement: { background: 14, sanity: 12 },
    statBonus: { background: 5, sanity: 3 },
    tags: "meta,truth",
    ruleKill: true,
  },
  {
    id: "I-026",
    name: "无字厚皮书",
    ownerId: "N-011",
    description: "一本无字的厚皮书。赠予喜爱阅读的NPC会逐渐浮现其最渴望的知识。",
    origin: "夜读老人手中的书的「空白副本」。真本写满死者的名字，这本专门写给活人。",
    sideEffect: "书中知识会逐渐侵蚀读者的自我认知，慎赠。",
    value: "赠予喜爱阅读的NPC可大幅增加好感。",
    statRequirement: { charm: 7 },
    statBonus: { charm: 2 },
    tags: "gift,favor",
  },
  // ===== N-012 厨师 3件 =====
  {
    id: "I-027",
    name: "屠夫菜刀",
    ownerId: "N-012",
    description: "沾满暗红污渍的菜刀。在与管道屠夫对抗时使用。",
    origin: "厨师用持续的剁肉声和真正的肉味混淆屠夫的猎物气息。刀下的肉有一部分来自管道。",
    sideEffect: "持有时管道屠夫会感知到，可能提前凝聚。",
    value: "对管道屠夫造成物理伤害；可暂时阻断其凝聚。",
    statRequirement: { agility: 9, background: 4 },
    statBonus: {},
    tags: "weapon,corrosive",
  },
  {
    id: "I-028",
    name: "新鲜生肉",
    ownerId: "N-012",
    description: "一块来源不明的鲜红肉类。可分散屠夫或猎犬的注意。",
    origin: "厨师剁的肉。一部分来自管道，一部分来自「自愿捐献」的住户。",
    sideEffect: "携带会吸引诡异；食用会被屠夫视为同类，最终被邀请进入水管。",
    value: "分散管道屠夫或无头猎犬注意力。",
    statRequirement: { agility: 4 },
    tags: "bait,danger",
  },
  {
    id: "I-029",
    name: "工业级强碱疏通剂",
    ownerId: "N-012",
    description: "高浓度氢氧化钠制剂。对管道屠夫具强腐蚀作用。",
    origin: "厨师从管道维修处偷来的。他用这个在屠夫凝聚时泼向水管连接处。",
    sideEffect: "使用释放刺鼻气味，吸引其他诡异。",
    value: "暂时阻断屠夫从水源凝聚；可造成腐蚀伤害。",
    statRequirement: { background: 6, agility: 5 },
    tags: "chemical,corrosive",
  },
  // ===== N-013 钢琴师 2件 =====
  {
    id: "I-030",
    name: "无声琴键",
    ownerId: "N-013",
    description: "从钢琴上拆下的单键。按下无声，但脑海中会响起旋律。",
    origin: "钢琴师死前未弹完的曲子。他相信自己还未弹完，所以一直留在公寓。琴键保存着最后一刻的寂静。",
    sideEffect: "若你指定曲目并「听完」，你的心脏节奏将永远与曲子的节奏同步。",
    value: "可用来与钢琴师交易；制造无声诱饵。",
    statRequirement: { charm: 5, sanity: 4 },
    statBonus: { sanity: 1 },
    tags: "trade,sound",
  },
  {
    id: "I-031",
    name: "乐谱残页",
    ownerId: "N-013",
    description: "泛黄的乐谱，音符已褪色。",
    origin: "钢琴师未完成的作品。曲终时他倒下了，观众说他在弹完最后一个音符前就死了。",
    sideEffect: "试图弹奏会听见自己的心跳逐渐与谱子同步。",
    value: "赠还钢琴师可增加好感；可用来与音乐相关NPC交易。",
    statRequirement: { charm: 6 },
    tags: "memory,favor",
  },
  // ===== N-014 洗衣房阿姨 2件 =====
  {
    id: "I-032",
    name: "漂白剂",
    ownerId: "N-014",
    description: "工业漂白剂。可净化红水污染。",
    origin: "洗衣房阿姨用来洗「洗不干净的东西」。她是防污染应急协议时期的后勤人员，知道静置12小时的真相。",
    sideEffect: "接触皮肤会灼伤；过量使用会激怒管道屠夫。",
    value: "净化红水；暂时净化门缝或管道口的污染。",
    statRequirement: { background: 5, agility: 4 },
    tags: "chemical,purification",
  },
  {
    id: "I-033",
    name: "裂开的肥皂",
    ownerId: "N-014",
    description: "干裂的肥皂。可清洁手上的血污或粘液。",
    origin: "洗衣房剩下的。使用后肥皂会「吸收」污渍颜色，逐渐变红。",
    sideEffect: "用后肥皂会逐渐变红，最终破裂渗出。",
    value: "清洁污染；赠还洗衣房阿姨可增加好感。",
    statRequirement: { sanity: 4 },
    tags: "cleaning,consumable",
  },
  // ===== N-015 电梯工 2件 =====
  {
    id: "I-034",
    name: "电梯应急钥匙",
    ownerId: "N-015",
    description: "可强制开启电梯门的应急钥匙。",
    origin: "电梯工负责确保电梯不到达13楼。他拆过13楼按钮，第二天它会重新出现。钥匙是他最后的防线。",
    sideEffect: "在13楼走廊使用可能打开错误的门。",
    value: "强制开启电梯；可用来与电梯工交易。",
    statRequirement: { agility: 6 },
    statBonus: { agility: 1 },
    tags: "key,tool",
  },
  {
    id: "I-035",
    name: "锈蚀的扳手",
    ownerId: "N-015",
    description: "维修用扳手。可拆卸部分管道。",
    origin: "电梯工说「楼梯不是给活人走的」。他只用这个修电梯，从不碰管道。",
    sideEffect: "拆卸管道可能释放屠夫。",
    value: "拆卸管道；堵住漏水口。",
    statRequirement: { agility: 5 },
    tags: "tool,risky",
  },
  // ===== N-016~N-020 各2件 =====
  {
    id: "I-036",
    name: "失眠者手记",
    ownerId: "N-016",
    description: "记录墙的吞咽声的手记。可预判器官拟态墙出现。",
    origin: "失眠症患者整夜徘徊时写的。他的失眠是认知污染早期症状，他听见的吞咽声是真实的。",
    sideEffect: "阅读会开始听见墙的声响，难以入睡。",
    value: "预判拟态墙；赠还失眠症患者可增加好感。",
    statRequirement: { sanity: 5 },
    statBonus: { sanity: 1 },
    tags: "intel,favor",
  },
  {
    id: "I-037",
    name: "安眠药空瓶",
    ownerId: "N-016",
    description: "安眠药瓶，内无药片。",
    origin: "他曾尝试吃药入睡。服药者会在梦中被墙壁吞噬。他把药全倒了。",
    sideEffect: "装过红水的瓶子会渗出腐蚀液。",
    value: "可装少量液体；与失眠症患者交易。",
    statRequirement: { background: 3 },
    tags: "container,trade",
  },
  {
    id: "I-038",
    name: "茶壶",
    ownerId: "N-017",
    description: "红制服保洁员的茶壶。盛装从管道取出的沉淀物。",
    origin: "她曾是普通住户，因口渴饮用了红色自来水。她没有完全死亡，成为公寓消化系统的一部分。",
    sideEffect: "饮用者在7日内逐渐液化，流入下水道。剧毒。",
    value: "可用来毒杀或与特定NPC交易；切勿饮用。",
    statRequirement: { background: 7, charm: 5 },
    tags: "poison,hazard",
  },
  {
    id: "I-039",
    name: "巡逻记录簿",
    ownerId: "N-018",
    description: "无面保安的巡逻记录。记载倒行者活动规律。",
    origin: "他负责监控楼梯间倒行者。无面状态是长期与高维实体接触的「维度磨损」。",
    sideEffect: "在无镜子处阅读会感觉被注视。",
    value: "预判倒行者出现；赠还无面保安可增加好感。",
    statRequirement: { agility: 5, background: 4 },
    statBonus: { agility: 1 },
    tags: "intel,favor",
  },
  {
    id: "I-040",
    name: "反光徽章",
    ownerId: "N-018",
    description: "可映出完整面容的徽章。无面保安在昏暗处需此物才能被正确观察。",
    origin: "他的脸只能存在于镜像中。徽章是他与三维世界交流的桥梁。",
    sideEffect: "透过徽章看到的倒影有时会慢半拍。",
    value: "与无面保安安全交流；可短暂固定倒行者身影。",
    statRequirement: { sanity: 6 },
    statBonus: { sanity: 1 },
    tags: "mirror,exorcism",
  },
  {
    id: "I-041",
    name: "调查笔记",
    ownerId: "N-019",
    description: "前调查员的手写笔记。含高维拟态肠胃推测。",
    origin: "他来自上世纪80年代秘密研究机构。同事全失踪了。笔记中哪些是发现、哪些是公寓植入的假情报，他已分不清。",
    sideEffect: "阅读会混淆真实与虚假记忆。",
    value: "知晓公寓部分真相；可用来与调查员交易；规则类杀伤参考。",
    statRequirement: { background: 12, sanity: 10 },
    statBonus: { background: 4 },
    tags: "meta,intel",
    blockLethal: true,
    ruleKill: true,
  },
  {
    id: "I-042",
    name: "录音笔",
    ownerId: "N-019",
    description: "磨损的录音设备。录下过墙内的声音。",
    origin: "他录下过墙内「布线」的脉动。回放时能听见消化系统的节奏。",
    sideEffect: "回放会吸引器官拟态墙的注意。",
    value: "预判拟态墙；与调查员交易。",
    statRequirement: { background: 5 },
    tags: "intel,risky",
  },
  {
    id: "I-043",
    name: "入住须知",
    ownerId: "N-020",
    description: "物业统一发放的入住须知。她会「不小心」漏掉关键几条。",
    origin: "新住户引导员是公寓的诱饵。正式员工都已被消化了，她胸口的「实习」徽章永远不会换。",
    sideEffect: "阅读会增加对引导员的信任，容易放松警惕。",
    value: "了解基础规则；可用来与引导员周旋。",
    statRequirement: { background: 4 },
    tags: "intel,trap",
  },
  {
    id: "I-044",
    name: "实习徽章",
    ownerId: "N-020",
    description: "引导员胸口的「实习」徽章。",
    origin: "正式员工的徽章会换成另一种——刻着消化周期的那种。她的永远不会换。",
    sideEffect: "佩戴会被物业视为「待消化新人」。",
    value: "伪装成新员工；可糊弄部分NPC。",
    statRequirement: { charm: 7, background: 5 },
    tags: "disguise,risky",
  },
  // ===== A-001 时差症候群 1件 =====
  {
    id: "I-045",
    name: "倒转的挂历页",
    ownerId: "A-001",
    description: "从时差症候群中脱落的挂历页。页码倒序。",
    origin: "时钟倒转时，墙壁上的挂历页飞速翻动。若在停止前扯下一页，可带出时间碎片。",
    sideEffect: "持有时影子与动作会产生延迟，最终影子可能先行。",
    value: "短暂篡改局部时间流速；可抵抗时差症候群因果侵蚀。",
    statRequirement: { luck: 8, sanity: 5 },
    statBonus: { luck: 2 },
    tags: "time,fragment",
  },
  // ===== A-002 无头猎犬 2件 =====
  {
    id: "I-046",
    name: "猎犬的声带",
    ownerId: "A-002",
    description: "无头猎犬体内取出的声带残块。可模仿大黄的叫声。",
    origin: "猎犬吞噬导盲犬大黄后，声带融合了大黄的声音。击杀猎犬时有机会取得。",
    sideEffect: "使用会暴露位置；但可短暂迷惑其他猎犬。",
    value: "制造诱饵叫声；可对猎犬造成短暂困惑。",
    statRequirement: { agility: 5 },
    tags: "bait,sound",
  },
  {
    id: "I-047",
    name: "漆黑粘液",
    ownerId: "A-002",
    description: "猎犬颈断处滴落的黑色粘液。可隔绝气息。",
    origin: "猎犬凭听觉追溯因果。粘液曾包裹其「听觉」，可短暂屏蔽因果链。",
    sideEffect: "涂抹后会逐渐渗入皮肤，24小时内需洗净。",
    value: "短暂屏蔽因果追踪；涂抹门缝可隔绝气味。",
    statRequirement: { agility: 6 },
    tags: "stealth,consumable",
  },
  // ===== A-003 认知腐蚀者 2件 =====
  {
    id: "I-048",
    name: "扭曲的告示碎片",
    ownerId: "A-003",
    description: "认知腐蚀者扭曲文字后脱落的碎片。可反向解析扭曲规则。",
    origin: "腐蚀者将告示扭曲成无法解读的符号。击杀后碎片会短暂保留「逆写」能力。",
    sideEffect: "直视碎片超过5秒会混淆自我认知。",
    value: "解读扭曲文字；可对认知腐蚀者施加规则类反击。",
    statRequirement: { sanity: 10, background: 6 },
    statBonus: { sanity: 1 },
    tags: "cognition,rules",
  },
  {
    id: "I-049",
    name: "虚假记忆结晶",
    ownerId: "A-003",
    description: "高维污染的固态残留。可植入短暂虚假记忆。",
    origin: "腐蚀者灌输的虚假记忆中，有一部分会结晶化。可用来糊弄其他诡异。",
    sideEffect: "使用会短暂忘记一段真实记忆。",
    value: "对NPC施加短暂认知干扰；可规避一次认知判定。",
    statRequirement: { sanity: 8, charm: 5 },
    tags: "cognition,consumable",
  },
  // ===== A-004 管道屠夫 2件 =====
  {
    id: "I-050",
    name: "未消化的钥匙",
    ownerId: "A-004",
    description: "从管道「排泄物」中捡回的钥匙。表面有半透明生物膜。",
    origin: "屠夫无法消化的金属。能打开公寓内任意一扇「未完全消化」的门。",
    sideEffect: "钥匙仍在轻微蠕动；可能打开错误的门。",
    value: "打开任意未消化门；可通往隐藏区域。",
    statRequirement: { luck: 9, agility: 6 },
    statBonus: { luck: 2, agility: 2 },
    tags: "key,digestion",
  },
  {
    id: "I-051",
    name: "消化膜碎片",
    ownerId: "A-004",
    description: "屠夫凝聚体的边缘碎片。可暂时阻断水源连接。",
    origin: "屠夫无法离开水源3米。碎片保留这一规则，可反向使用。",
    sideEffect: "持有时水管会渗出更多红色液体。",
    value: "撒向屠夫根部可暂时瘫痪约30秒。",
    statRequirement: { agility: 7 },
    tags: "chemical,corrosive",
  },
  // ===== A-005 器官拟态墙 1件 =====
  {
    id: "I-052",
    name: "墙上的眼膜",
    ownerId: "A-005",
    description: "从拟态墙眼睛上剥离的膜。可短暂遮蔽视线。",
    origin: "与墙上的眼睛对视超过3秒会被吞噬。剥离的眼膜保留「遮蔽」能力。",
    sideEffect: "使用后自己的视线会模糊10分钟。",
    value: "遮蔽诡异视线；可暂时屏蔽拟态墙的凝视。",
    statRequirement: { agility: 6, sanity: 5 },
    tags: "conceal,consumable",
  },
  // ===== A-006 倒行者 2件 =====
  {
    id: "I-053",
    name: "破裂的八卦镜",
    ownerId: "A-006",
    description: "碎裂的八卦镜。可短暂固定倒行者的身影。",
    origin: "倒行者后脑勺光滑如镜，映出你的位置。用镜子对镜可短暂固定其身影。",
    sideEffect: "每使用一次裂痕加深，三次后彻底碎裂。",
    statRequirement: { sanity: 7 },
    statBonus: { sanity: 1 },
    value: "固定倒行者3秒；抵挡一次方向感倒转。",
    tags: "mirror,exorcism",
  },
  {
    id: "I-054",
    name: "倒行的脚印",
    ownerId: "A-006",
    description: "倒行者留下的脚印拓片。方向与正常相反。",
    origin: "倒行者脚掌与台阶方向相反。拓下的脚印可用来「逆写」方向感。",
    sideEffect: "持有时会偶尔搞错左右。",
    value: "可短暂逆转诡异的方向判定；用于逃脱。",
    statRequirement: { agility: 6, luck: 5 },
    tags: "trap,consumable",
  },
  // ===== A-007 13楼门扉 1件 =====
  {
    id: "I-055",
    name: "13楼的门把手",
    ownerId: "A-007",
    description: "从13楼某扇门上拆下的把手。门内传来你的声音。",
    origin: "门内呼唤你的名字。把手是未消化层的「入口」残留。持有者可短暂屏蔽与13楼的因果。",
    sideEffect: "持有时会听见门内传来自己的声音呼唤。",
    value: "屏蔽与13楼门扉的因果关联一次；配合信封使用更佳。",
    statRequirement: { luck: 11, sanity: 8 },
    tags: "key,consumable",
  },
  // ===== A-008 深渊守门人 3件 =====
  {
    id: "I-056",
    name: "防污染应急协议残页",
    ownerId: "A-008",
    description: "上世纪80年代秘密机构遗留的协议碎片。记载红水静置、镜子遮挡等核心规则。",
    origin: "守门人由无数住户残影叠合而成。击杀时有机会从残影中剥离协议碎片。",
    sideEffect: "阅读会看见自己的脸出现在某页残影中。",
    value: "抵挡一次致命攻击；可利用规则对诡异施加规则类杀伤。",
    statRequirement: { background: 13, sanity: 11 },
    statBonus: { background: 4 },
    tags: "protocol,rules",
    blockLethal: true,
    ruleKill: true,
  },
  {
    id: "I-057",
    name: "符纸护身符",
    ownerId: "A-008",
    description: "不知名道士留下的黄符。朱砂字迹已褪色。",
    origin: "守门人守卫B2出口。曾有道士试图封印，失败后符纸散落。可抵挡守门人单次攻击。",
    sideEffect: "使用后符纸自燃成灰。",
    value: "抵挡一次致命攻击（含守门人）。",
    statRequirement: { sanity: 8 },
    statBonus: { sanity: 2 },
    tags: "protection,exorcism",
    blockLethal: true,
  },
  {
    id: "I-058",
    name: "染血的如月建筑原稿",
    ownerId: "A-008",
    description: "泛黄建筑设计图，边缘浸染暗红污渍。标注了公寓的真实结构。",
    origin: "承重墙=骨骼投影，水管=消化管道。知晓结构者可利用规则漏洞跨越战力鸿沟对诡异施加致命一击。",
    sideEffect: "阅读会逐渐理解公寓在「消化」你。",
    value: "利用规则漏洞对诡异施加致命一击；无视战力差距。",
    statRequirement: { background: 15, sanity: 13 },
    statBonus: { background: 5, sanity: 3 },
    tags: "meta,truth",
    ruleKill: true,
  },
  {
    id: "I-059",
    name: "深色遮光布",
    ownerId: "A-006",
    description: "足够遮盖镜子的厚重布料。凌晨2点后遮挡镜子可避免与倒行者视觉接触。",
    origin: "倒行者后脑勺光滑如镜。遮住镜子即遮住其「视线」。布料会逐渐吸收镜中残留影像。",
    sideEffect: "布料会逐渐变重，最终无法掀开。",
    value: "遮挡镜子避免倒行者接触；对器官拟态墙眼睛有效。",
    statRequirement: { sanity: 5 },
    tags: "mirror,cover",
  },
  // ===== 羊皮纸（开局固定）=====
  {
    id: "I-PARCHMENT",
    name: "染血的羊皮纸",
    ownerId: "A-008",
    description: "三日之后暗月降至；十日之后一切终焉。本层徘徊着未知的诡异，不要相信轻易示好的住客。暗月期间不要直视光源。",
    origin: "守门人结界边缘散落的规则碎片。被消化前的住户用血写下的生存法则，半真半假。",
    sideEffect: "阅读后会被公寓「标记」，消化优先级微升。",
    value: "知晓基础规则；开局必读。",
    statBonus: {},
    tags: "lore,truth",
  },
];

export const DROPPABLE_ITEM_IDS = ITEMS.filter((i) => i.canFindOnRoad).map((i) => i.id);
export const ITEMS_BY_ID = Object.fromEntries(ITEMS.map((i) => [i.id, i]));
