// src/lib/registry/items.ts
// 如月公寓物品注册表 - 81 件 (S1/A3/B10/C17/D50)

import type { Item } from "./types";

export const ITEMS: readonly Item[] = [
  // === S级 1个：全属性≥20 ===
  {
    id: "I-S01",
    name: "染血的如月建筑原稿",
    tier: "S",
    description:
      "一份泛黄的建筑设计图，边缘浸染暗红色污渍。图纸标注了如月公寓的「真实结构」——承重墙被标为「骨骼投影」，水管网络被标为「消化管道」。知晓结构者可利用规则漏洞，跨越战力鸿沟对诡异施加致命一击。",
    statBonus: { background: 5, sanity: 3 },
    tags: "meta,truth",
    statRequirements: { sanity: 20, agility: 20, luck: 20, charm: 20, background: 20 },
    ownerId: "N-011",
    effectType: "ruleKill",
    ruleKill: true,
  },
  // === A级 3个：单项≥20 ===
  {
    id: "I-A01",
    name: "停止转动的怀表",
    tier: "A",
    description:
      "一枚古董怀表，秒针永久停在 2:47。使用后可在接下来 1 小时内临时获得幸运+5，且时间感知不受时差症候群侵蚀。秒针会微微颤动，仿佛在倒流。",
    statBonus: { luck: 3, sanity: 2 },
    tags: "time,rewind",
    statRequirements: { luck: 20 },
    ownerId: "A-001",
    effectType: "tempStat",
    tempStatEffect: { stat: "luck", value: 5 },
  },
  {
    id: "I-A02",
    name: "防污染应急协议残页",
    tier: "A",
    description:
      "上世纪 80 年代秘密研究机构遗留的协议碎片。使用后可抵挡一次致命攻击（包括 B2 守门人）；或对诡异施加规则类杀伤。使用后残页化为灰烬。",
    statBonus: { background: 4 },
    tags: "protocol,rules",
    statRequirements: { background: 20 },
    ownerId: "N-019",
    effectType: "shield",
    blockLethal: true,
    ruleKill: true,
  },
  {
    id: "I-A03",
    name: "未消化的钥匙",
    tier: "A",
    description:
      "一把从公寓某处「排泄物」中捡回的金属钥匙。使用后可打开公寓内任意一扇「未完全消化」的门，包括部分被封禁的房间。钥匙用后会溶解。",
    statBonus: { luck: 2, agility: 2 },
    tags: "key,digestion",
    statRequirements: { agility: 20 },
    ownerId: "A-004",
    effectType: "key",
  },
  // === B级：单项 10-15 ===
  {
    id: "I-B01",
    name: "沾染腥味的狗绳",
    tier: "B",
    description:
      "一条褪色的皮质狗绳。使用后向指定方向抛出，无头猎犬会被其气息吸引并产生短暂困惑，为你争取 30 秒逃生时间。",
    statBonus: { agility: 2 },
    tags: "beast,memory",
    statRequirements: { agility: 12 },
    ownerId: "A-002",
    effectType: "bait",
  },
  {
    id: "I-B02",
    name: "陈婆婆的毛线团",
    tier: "B",
    description:
      "一团未织完的毛线。使用后可在 1 分钟内将小型诡异实体（如认知污染扩散体）缠绕束缚，无法移动。使用后毛线会「长」入指尖，24 小时内需用剪刀切断。",
    statBonus: { charm: 1 },
    tags: "binding,trap",
    statRequirements: { charm: 10 },
    ownerId: "N-001",
    effectType: "binding",
  },
  {
    id: "I-B03",
    name: "林医生的听诊器",
    tier: "B",
    description:
      "使用后临时获得出身+3 持续 2 小时，可预判器官拟态墙的出现位置。长时间佩戴会听见自己的心跳变慢，需及时取下。",
    statBonus: { background: 2 },
    tags: "diagnostic,sound",
    statRequirements: { background: 12 },
    ownerId: "N-002",
    effectType: "tempStat",
    tempStatEffect: { stat: "background", value: 3 },
  },
  {
    id: "I-B04",
    name: "邮差的空白信封",
    tier: "B",
    description:
      "将某 NPC 名字写在信封上后使用，可短暂屏蔽其与 13 楼门扉的因果关联 1 小时。信封使用后会自动填满讣告内容并失效。",
    statBonus: { luck: 2 },
    tags: "mail,isolation",
    statRequirements: { luck: 12 },
    ownerId: "N-003",
    effectType: "tempFavor",
    tempFavorEffect: 0,
  },
  {
    id: "I-B05",
    name: "夜读老人的书签",
    tier: "B",
    description:
      "使用后 30 分钟内可幻化为夜读老人的外表，认知腐蚀者难以定位你，理智消耗减半。书签会逐渐显现你的名字，使用超过 2 次后失效。",
    statBonus: { sanity: 1 },
    tags: "conceal,cognition",
    statRequirements: { sanity: 12 },
    ownerId: "N-011",
    effectType: "transform",
    transformTargetId: "N-011",
  },
  // === C级：单项 5-10 ===
  {
    id: "I-C01",
    name: "工业级强碱疏通剂",
    tier: "C",
    description:
      "使用后对管道屠夫造成强腐蚀，暂时阻断其从水源凝聚约 30 秒。释放刺鼻气味会吸引其他诡异，需迅速撤离。",
    statBonus: {},
    tags: "chemical,corrosive",
    statRequirements: { agility: 7 },
    ownerId: "N-008",
    effectType: "purify",
  },
  {
    id: "I-C02",
    name: "破裂的八卦镜",
    tier: "C",
    description:
      "使用后可短暂「固定」楼梯间倒行者的身影 60 秒，使其无法移动。镜面每用一次裂痕加深，三次后碎裂。",
    statBonus: { sanity: 1 },
    tags: "mirror,exorcism",
    statRequirements: { sanity: 7 },
    ownerId: "A-006",
    effectType: "binding",
  },
  {
    id: "I-C03",
    name: "防爆手电筒",
    tier: "C",
    description:
      "使用后 2 小时内驱散认知污染产生的幻觉，理智消耗减半。强光会惊动无头猎犬，4 楼禁用。",
    statBonus: { agility: 1 },
    tags: "light,tool",
    statRequirements: { agility: 5 },
    ownerId: "N-018",
    effectType: "purify",
  },
  {
    id: "I-C04",
    name: "符纸护身符",
    tier: "C",
    description:
      "使用后可抵挡一次致命攻击（含 B2 守门人）。符纸自燃成灰后失效。",
    statBonus: { sanity: 2 },
    tags: "protection,exorcism",
    statRequirements: { sanity: 10 },
    ownerId: "N-019",
    effectType: "shield",
    blockLethal: true,
  },
  {
    id: "I-C05",
    name: "机械腕表",
    tier: "C",
    description:
      "使用后 4 小时内抵抗时差症候群的因果侵蚀，时间感知正常。电池耗尽需前往保安室更换。",
    statBonus: { sanity: 1 },
    tags: "time,reference",
    statRequirements: { sanity: 5 },
    ownerId: "N-010",
    effectType: "tempStat",
    tempStatEffect: { stat: "sanity", value: 2 },
  },
  {
    id: "I-C06",
    name: "深色遮光布",
    tier: "C",
    description:
      "遮挡镜子使用，可避免与倒行者发生视觉接触，持续至下次午夜。布料会逐渐吸收镜中残留影像，用后需更换。",
    statBonus: {},
    tags: "mirror,cover",
    statRequirements: { agility: 5 },
    ownerId: "N-009",
    effectType: "purify",
  },
  {
    id: "I-C07",
    name: "石灰粉包",
    tier: "C",
    description:
      "撒向管道屠夫「根部」可暂时瘫痪其行动约 30 秒。用后无法回收。",
    statBonus: {},
    tags: "chemical,corrosive",
    statRequirements: { agility: 7 },
    ownerId: "N-012",
    effectType: "purify",
  },
  {
    id: "I-C08",
    name: "耳塞",
    tier: "C",
    description:
      "佩戴后屏蔽 4 楼狗叫与部分墙壁蠕动声 1 小时，理智消耗减半。若已回应过狗叫则无效。",
    statBonus: { sanity: 1 },
    tags: "sound,protection",
    statRequirements: { sanity: 5 },
    ownerId: "N-005",
    effectType: "shield",
  },
  {
    id: "I-C09",
    name: "盐袋",
    tier: "C",
    description:
      "撒在门缝或管道口可暂时净化污染 2 小时，对管道屠夫有驱散效果。用量有限，约 3 次。",
    statBonus: {},
    tags: "chemical,purification",
    statRequirements: { sanity: 5 },
    ownerId: "N-014",
    effectType: "purify",
  },
  {
    id: "I-C10",
    name: "折叠刀",
    tier: "C",
    description:
      "可切割绳索、开罐头。切勿用于对抗诡异——会激发管道屠夫的「食材」判定。使用后临时敏捷+1 持续 30 分钟。",
    statBonus: { agility: 1 },
    tags: "tool,utility",
    statRequirements: { agility: 5 },
    ownerId: "N-012",
    effectType: "tempStat",
    tempStatEffect: { stat: "agility", value: 1 },
  },
  // === D级：单项≥3 ===
  {
    id: "I-D01",
    name: "过期罐头",
    tier: "D",
    description: "食用可恢复少量理智（+1），30% 概率食物中毒导致敏捷-1 持续 1 小时。",
    statBonus: {},
    tags: "consumable,risky",
    statRequirements: { sanity: 3 },
    ownerId: "N-012",
    effectType: "consumable",
  },
  {
    id: "I-D02",
    name: "新鲜生肉",
    tier: "D",
    description: "抛出可分散管道屠夫或无头猎犬注意 15 秒。携带会吸引诡异靠近。",
    statBonus: {},
    tags: "bait,danger",
    statRequirements: { agility: 3 },
    ownerId: "A-004",
    effectType: "bait",
  },
  {
    id: "I-D03",
    name: "发霉面包",
    tier: "D",
    description: "食用后理智-1，但 1 小时内可混淆认知腐蚀者的味觉追踪。",
    statBonus: { sanity: -1 },
    tags: "consumable,tainted",
    statRequirements: { sanity: 3 },
    ownerId: "A-003",
    effectType: "consumable",
  },
  {
    id: "I-D04",
    name: "锈蚀的螺丝钉",
    tier: "D",
    description: "可临时堵住漏水水龙头，锈迹会污染水质，红水静置时间需延长至 24 小时。",
    statBonus: {},
    tags: "junk,utility",
    statRequirements: { background: 3 },
    ownerId: "N-008",
    effectType: "consumable",
  },
  {
    id: "I-D05",
    name: "皱巴巴的报纸",
    tier: "D",
    description: "包裹物品可隔绝气息 1 小时。报纸会逐渐更新成与你相关的噩耗。",
    statBonus: {},
    tags: "wrapper,ominous",
    statRequirements: { luck: 3 },
    ownerId: "N-006",
    effectType: "consumable",
  },
  {
    id: "I-D06",
    name: "一次性纸杯",
    tier: "D",
    description: "可盛放静置后的红水。纸杯会逐渐渗红，用后尽快丢弃。",
    statBonus: {},
    tags: "container,disposable",
    statRequirements: { agility: 3 },
    ownerId: "N-010",
    effectType: "consumable",
  },
  {
    id: "I-D07",
    name: "断裂的铅笔",
    tier: "D",
    description: "可做记号或书写，字迹 1 小时后扭曲。",
    statBonus: {},
    tags: "writing,cursed",
    statRequirements: { background: 3 },
    ownerId: "N-006",
    effectType: "consumable",
  },
  {
    id: "I-D08",
    name: "褪色照片",
    tier: "D",
    description: "抛出可短暂吸引部分诡异注意 10 秒。凝视超过 10 秒会看见人影移动，理智-1。",
    statBonus: { sanity: -1 },
    tags: "memory,bait",
    statRequirements: { luck: 3 },
    ownerId: "A-003",
    effectType: "bait",
  },
  {
    id: "I-D09",
    name: "空药瓶",
    tier: "D",
    description: "可装盛少量液体。装过红水的瓶子会持续渗出腐蚀液。",
    statBonus: {},
    tags: "container,hazard",
    statRequirements: { agility: 3 },
    ownerId: "N-002",
    effectType: "consumable",
  },
  {
    id: "I-D10",
    name: "脏兮兮的抹布",
    tier: "D",
    description: "擦拭镜面后镜子会映出错误倒影。不建议用于遮挡。",
    statBonus: {},
    tags: "cleaning,cursed",
    statRequirements: { sanity: 3 },
    ownerId: "N-017",
    effectType: "consumable",
  },
  {
    id: "I-D11",
    name: "干瘪的橙子",
    tier: "D",
    description: "食用可恢复微量理智（+1）。果肉内可能藏有消化残留，有 20% 概率理智-1。",
    statBonus: { sanity: 1 },
    tags: "consumable,tainted",
    statRequirements: { sanity: 3 },
    ownerId: "N-012",
    effectType: "consumable",
  },
  {
    id: "I-D12",
    name: "塑料打火机",
    tier: "D",
    description: "可点燃符纸或制造光源。器官拟态墙附近使用可能激怒墙壁。",
    statBonus: {},
    tags: "fire,risky",
    statRequirements: { agility: 3 },
    ownerId: "N-019",
    effectType: "consumable",
  },
  {
    id: "I-D13",
    name: "磨损的拖鞋",
    tier: "D",
    description: "穿着可减少脚步声 1 小时，敏捷+1。鞋底会留下粘液痕迹，可能被追踪。",
    statBonus: { agility: 1 },
    tags: "footwear,stealth",
    statRequirements: { agility: 3 },
    ownerId: "N-016",
    effectType: "tempStat",
    tempStatEffect: { stat: "agility", value: 1 },
  },
  {
    id: "I-D14",
    name: "生锈的钥匙",
    tier: "D",
    description: "可能打开某扇废弃房间——也可能打开 13 楼。使用前请三思。",
    statBonus: {},
    tags: "key,unknown",
    statRequirements: { luck: 3 },
    ownerId: "N-015",
    effectType: "key",
  },
  {
    id: "I-D15",
    name: "皱褶的便签纸",
    tier: "D",
    description: "可记录规则或留讯息。字迹会在无人注视时悄悄改变。",
    statBonus: {},
    tags: "writing,unreliable",
    statRequirements: { background: 3 },
    ownerId: "N-006",
    effectType: "consumable",
  },
  {
    id: "I-D16",
    name: "浑浊的矿泉水",
    tier: "D",
    description: "饮用缓解口渴，理智+1。10% 概率是红水稀释版，理智-2。",
    statBonus: { sanity: -1 },
    tags: "consumable,risky",
    statRequirements: { sanity: 3 },
    ownerId: "N-020",
    effectType: "consumable",
  },
  {
    id: "I-D17",
    name: "断线的耳机",
    tier: "D",
    description: "佩戴可屏蔽部分噪音 30 分钟，但会听到细微耳语，理智-1。",
    statBonus: { sanity: -1 },
    tags: "sound,mixed",
    statRequirements: { sanity: 3 },
    ownerId: "N-016",
    effectType: "consumable",
  },
  {
    id: "I-D18",
    name: "破洞的塑料袋",
    tier: "D",
    description: "包裹生肉等物品可短暂隔绝气味 20 分钟，效果有限。",
    statBonus: {},
    tags: "wrapper,weak",
    statRequirements: { agility: 3 },
    ownerId: "N-014",
    effectType: "consumable",
  },
  {
    id: "I-D19",
    name: "发条玩具",
    tier: "D",
    description: "使用后可制造声响吸引无头猎犬 15 秒——但会吸引它朝声源移动。慎用。",
    statBonus: {},
    tags: "bait,sound",
    statRequirements: { agility: 3 },
    ownerId: "N-004",
    effectType: "bait",
  },
  {
    id: "I-D20",
    name: "褪色明信片",
    tier: "D",
    description: "使用后邮差老王跳过你一次投递判定。明信片 1 小时后消失。",
    statBonus: {},
    tags: "mail,consumable",
    statRequirements: { charm: 3 },
    ownerId: "N-003",
    effectType: "consumable",
  },
  {
    id: "I-D21",
    name: "裂开的肥皂",
    tier: "D",
    description: "清洁血污或粘液，使用后肥皂逐渐变红。",
    statBonus: {},
    tags: "cleaning,absorbent",
    statRequirements: { sanity: 3 },
    ownerId: "N-014",
    effectType: "consumable",
  },
  {
    id: "I-D22",
    name: "无电池的遥控器",
    tier: "D",
    description: "按下可发出咔哒声，测试周围是否有依赖听觉的诡异。",
    statBonus: {},
    tags: "tool,test",
    statRequirements: { luck: 3 },
    ownerId: "N-007",
    effectType: "consumable",
  },
  {
    id: "I-D23",
    name: "发黄的纱布",
    tier: "D",
    description: "可包扎伤口，纱布会与伤口融合，拆除时造成二次伤害。",
    statBonus: {},
    tags: "medical,risky",
    statRequirements: { sanity: 3 },
    ownerId: "N-002",
    effectType: "consumable",
  },
  {
    id: "I-D24",
    name: "空罐头盒",
    tier: "D",
    description: "可当临时容器或制造声响。边缘锋利，使用不当可能划伤。",
    statBonus: {},
    tags: "container,junk",
    statRequirements: { agility: 3 },
    ownerId: "N-012",
    effectType: "consumable",
  },
  {
    id: "I-D25",
    name: "折断的梳子",
    tier: "D",
    description: "整理仪容可维持理智+1 持续 30 分钟。梳头会听见不属于自己的头发被扯断声。",
    statBonus: { sanity: 0 },
    tags: "personal,uncanny",
    statRequirements: { charm: 3 },
    ownerId: "N-007",
    effectType: "tempStat",
    tempStatEffect: { stat: "sanity", value: 1 },
  },
  {
    id: "I-D26",
    name: "过期牛奶",
    tier: "D",
    description: "饮用敏捷-2 持续 1 小时。可用来污染红水，使其暂时失去腐蚀性。",
    statBonus: { agility: -2 },
    tags: "consumable,chemical",
    statRequirements: { background: 3 },
    ownerId: "N-014",
    effectType: "consumable",
  },
  {
    id: "I-D27",
    name: "掉色的窗帘绳",
    tier: "D",
    description: "可捆绑或做简易陷阱。绳子会逐渐收紧，长时间捆绑会勒入皮肉。",
    statBonus: {},
    tags: "binding,danger",
    statRequirements: { agility: 3 },
    ownerId: "N-019",
    effectType: "consumable",
  },
  {
    id: "I-D28",
    name: "碎镜片",
    tier: "D",
    description: "握持可短暂看见真实倒影，理智+1。碎片会割伤手掌，每次使用都会缩小。",
    statBonus: { sanity: 1 },
    tags: "mirror,fragment",
    statRequirements: { sanity: 3 },
    ownerId: "A-006",
    effectType: "tempStat",
    tempStatEffect: { stat: "sanity", value: 1 },
  },
  {
    id: "I-D29",
    name: "漏水的钢笔",
    tier: "D",
    description: "可用于签署不重要文件糊弄物业。字迹会随时间扩散。",
    statBonus: {},
    tags: "writing,unreliable",
    statRequirements: { background: 3 },
    ownerId: "N-010",
    effectType: "consumable",
  },
  {
    id: "I-D30",
    name: "瘪掉的篮球",
    tier: "D",
    description: "拍打可制造声响掩盖心跳 5 分钟，但规律声响会吸引无头猎犬。",
    statBonus: {},
    tags: "sound,double-edged",
    statRequirements: { agility: 3 },
    ownerId: "N-004",
    effectType: "bait",
  },
  {
    id: "I-D31",
    name: "发黑的银币",
    tier: "D",
    description: "投入物业许愿池可换取一次「投币问路」。池底会传来咀嚼声。",
    statBonus: {},
    tags: "coin,omen",
    statRequirements: { luck: 3 },
    ownerId: "N-010",
    effectType: "consumable",
  },
  {
    id: "I-D32",
    name: "褪色的红绳",
    tier: "D",
    description: "佩戴可短暂延缓认知腐蚀者定位 15 分钟。气息隔绝效果微弱。",
    statBonus: { sanity: 0 },
    tags: "charm,weak",
    statRequirements: { sanity: 3 },
    ownerId: "N-001",
    effectType: "shield",
  },
  {
    id: "I-D33",
    name: "黏糊的糖纸",
    tier: "D",
    description: "贴门缝可隔绝气味 15 分钟，但会吸引嗜甜诡异。",
    statBonus: {},
    tags: "wrapper,bait",
    statRequirements: { agility: 3 },
    ownerId: "N-004",
    effectType: "consumable",
  },
  {
    id: "I-D34",
    name: "生锈的别针",
    tier: "D",
    description: "可固定衣角或修补。针尖沾血，携带可能引发猎物判定。",
    statBonus: {},
    tags: "tool,risky",
    statRequirements: { background: 3 },
    ownerId: "N-002",
    effectType: "consumable",
  },
  {
    id: "I-D35",
    name: "裂开的粉饼",
    tier: "D",
    description: "使用后 30 分钟内理智+1。粉底会逐渐变红。",
    statBonus: { sanity: 0 },
    tags: "personal,uncanny",
    statRequirements: { charm: 3 },
    ownerId: "N-007",
    effectType: "tempStat",
    tempStatEffect: { stat: "sanity", value: 1 },
  },
  {
    id: "I-D36",
    name: "空火柴盒",
    tier: "D",
    description: "擦燃可产生微光。火光会映出不该存在的影子。",
    statBonus: {},
    tags: "fire,vision",
    statRequirements: { luck: 3 },
    ownerId: "N-019",
    effectType: "consumable",
  },
  {
    id: "I-D37",
    name: "湿漉漉的鞋垫",
    tier: "D",
    description: "塞门缝可延缓管道屠夫凝聚 20 分钟。鞋垫会逐渐「活」过来。",
    statBonus: {},
    tags: "absorbent,danger",
    statRequirements: { agility: 3 },
    ownerId: "A-004",
    effectType: "purify",
  },
  {
    id: "I-D38",
    name: "缺页的日历",
    tier: "D",
    description: "可参考时间。日期会在无人注视时改变。",
    statBonus: {},
    tags: "time,unreliable",
    statRequirements: { sanity: 3 },
    ownerId: "N-006",
    effectType: "consumable",
  },
  {
    id: "I-D39",
    name: "半瓶漱口水",
    tier: "D",
    description: "含口中可屏蔽腐臭 15 分钟。吞咽会导致喉咙锁死感。",
    statBonus: {},
    tags: "consumable,mixed",
    statRequirements: { sanity: 3 },
    ownerId: "N-002",
    effectType: "consumable",
  },
  {
    id: "I-D40",
    name: "断掉的橡皮筋",
    tier: "D",
    description: "可捆扎小物。橡皮筋会逐渐缩紧，勒入物体内部。",
    statBonus: {},
    tags: "binding,creepy",
    statRequirements: { agility: 3 },
    ownerId: "N-001",
    effectType: "consumable",
  },
  {
    id: "I-D41",
    name: "发霉的茶叶",
    tier: "D",
    description: "泡水饮用理智+1。有概率触发记忆闪回，理智-1。",
    statBonus: { sanity: -1 },
    tags: "consumable,tainted",
    statRequirements: { sanity: 3 },
    ownerId: "N-017",
    effectType: "consumable",
  },
  {
    id: "I-D42",
    name: "歪斜的相框",
    tier: "D",
    description: "放入照片后，相框会逐渐修正照片内容以符合公寓叙事。",
    statBonus: {},
    tags: "memory,cursed",
    statRequirements: { sanity: 3 },
    ownerId: "A-003",
    effectType: "consumable",
  },
  {
    id: "I-D43",
    name: "掉漆的拨浪鼓",
    tier: "D",
    description: "摇动可吸引或分散诡异注意 10 秒。长时间使用会听见婴儿啼哭。",
    statBonus: {},
    tags: "sound,bait",
    statRequirements: { luck: 3 },
    ownerId: "N-009",
    effectType: "bait",
  },
  {
    id: "I-D44",
    name: "卷曲的指甲剪",
    tier: "D",
    description: "剪下的指甲必须立刻烧掉，否则会吸引收集者诡异。",
    statBonus: {},
    tags: "personal,taboo",
    statRequirements: { charm: 3 },
    ownerId: "N-013",
    effectType: "consumable",
  },
  {
    id: "I-D45",
    name: "漏气的打火机",
    tier: "D",
    description: "可勉强点燃符纸，火焰呈蓝色，可能引发小型爆燃。",
    statBonus: {},
    tags: "fire,risky",
    statRequirements: { agility: 3 },
    ownerId: "N-008",
    effectType: "consumable",
  },
  {
    id: "I-D46",
    name: "发黄的绷带",
    tier: "D",
    description: "包扎可止血。绷带会与皮肤融合，24 小时后难以撕除。",
    statBonus: {},
    tags: "medical,risky",
    statRequirements: { sanity: 3 },
    ownerId: "N-002",
    effectType: "consumable",
  },
  {
    id: "I-D47",
    name: "瘪掉的牙膏",
    tier: "D",
    description: "管身可装少量液体。装过红水会在一小时内蠕动。",
    statBonus: {},
    tags: "container,hazard",
    statRequirements: { agility: 3 },
    ownerId: "N-017",
    effectType: "consumable",
  },
  {
    id: "I-D48",
    name: "褪色的门牌",
    tier: "D",
    description: "挂门上可混淆邮差投递判定，使其跳过你一次。",
    statBonus: {},
    tags: "identity,consumable",
    statRequirements: { charm: 3 },
    ownerId: "N-003",
    effectType: "consumable",
  },
  {
    id: "I-D49",
    name: "开裂的塑料勺",
    tier: "D",
    description: "可舀取液体。接触红水会迅速溶解释放毒雾。",
    statBonus: {},
    tags: "tool,fragile",
    statRequirements: { background: 3 },
    ownerId: "N-012",
    effectType: "consumable",
  },
  {
    id: "I-D50",
    name: "无墨的印泥",
    tier: "D",
    description: "可伪造签名糊弄物业。印泥会逐渐渗血。",
    statBonus: {},
    tags: "writing,ominous",
    statRequirements: { background: 3 },
    ownerId: "N-010",
    effectType: "consumable",
  },
  {
    id: "I-C11",
    name: "铜铃铛",
    tier: "C",
    description: "摇响可驱散 3 米内低阶认知污染 30 秒。对无头猎犬无效且会暴露位置。",
    statBonus: { sanity: 1 },
    tags: "sound,exorcism",
    statRequirements: { sanity: 7 },
    ownerId: "N-001",
    effectType: "purify",
  },
  {
    id: "I-C12",
    name: "备用电池",
    tier: "C",
    description: "可恢复手电或机械表续航 2 小时。电池不带污染。",
    statBonus: {},
    tags: "utility,clean",
    statRequirements: { background: 5 },
    ownerId: "N-010",
    effectType: "consumable",
  },
  {
    id: "I-C13",
    name: "铁蒺藜",
    tier: "C",
    description: "撒在走廊可延缓人形诡异追击 1 分钟。对无实体诡异无效。用后难回收。",
    statBonus: { agility: 1 },
    tags: "trap,physical",
    statRequirements: { agility: 7 },
    ownerId: "N-018",
    effectType: "binding",
  },
  {
    id: "I-C14",
    name: "褪色护身符",
    tier: "C",
    description: "使用后一次精神污染的理智损伤减半。用后符纸碎裂。",
    statBonus: { sanity: 2 },
    tags: "protection,consumable",
    statRequirements: { sanity: 7 },
    ownerId: "N-001",
    effectType: "shield",
  },
  {
    id: "I-C15",
    name: "橡胶手套",
    tier: "C",
    description: "佩戴可徒手接触红水 30 分钟不受伤。手套会逐渐与皮肤粘连。",
    statBonus: {},
    tags: "protection,hazard",
    statRequirements: { agility: 5 },
    ownerId: "N-014",
    effectType: "shield",
  },
  {
    id: "I-C16",
    name: "便携灭火器",
    tier: "C",
    description: "可暂时窒息管道屠夫水雾形态 20 秒。用一次后耗尽。",
    statBonus: {},
    tags: "chemical,tool",
    statRequirements: { agility: 7 },
    ownerId: "N-008",
    effectType: "purify",
  },
  {
    id: "I-C17",
    name: "夜光贴纸",
    tier: "C",
    description: "贴墙可标记路线，黑暗中可见 4 小时。贴纸会逐渐显现诡异符号。",
    statBonus: {},
    tags: "marker,utility",
    statRequirements: { background: 5 },
    ownerId: "N-019",
    effectType: "consumable",
  },
  {
    id: "I-B06",
    name: "陈婆婆的织针",
    tier: "B",
    description: "归还或赠予陈婆婆或与织造相关的 NPC，可立即增加该 NPC 好感度 +15。",
    statBonus: { charm: 2 },
    tags: "gift,favor",
    statRequirements: { charm: 12 },
    ownerId: "N-001",
    effectType: "tempFavor",
    tempFavorEffect: 15,
  },
  {
    id: "I-B07",
    name: "林医生的处方笺",
    tier: "B",
    description: "写下某 NPC 名字并「开药」后赠予，可增加该 NPC 好感度 +12。仅限一次。",
    statBonus: { charm: 2 },
    tags: "gift,favor",
    statRequirements: { charm: 12 },
    ownerId: "N-002",
    effectType: "tempFavor",
    tempFavorEffect: 12,
  },
  {
    id: "I-B08",
    name: "邮差的挂号信",
    tier: "B",
    description: "填入某 NPC 名字并「送达」，可大幅增加该 NPC 好感度 +18。邮差因果会强制完成投递。",
    statBonus: { luck: 2 },
    tags: "gift,favor",
    statRequirements: { luck: 12 },
    ownerId: "N-003",
    effectType: "tempFavor",
    tempFavorEffect: 18,
  },
  {
    id: "I-B09",
    name: "保安的巡逻表",
    tier: "B",
    description: "使用后 2 小时内可精准规避巡逻。赠予对物业有敌意的 NPC 可增加其好感度 +10，换取合作。",
    statBonus: { agility: 2, background: 1 },
    tags: "intel,favor",
    statRequirements: { agility: 12 },
    ownerId: "N-018",
    effectType: "tempFavor",
    tempFavorEffect: 10,
  },
  {
    id: "I-B10",
    name: "夜读老人的书",
    tier: "B",
    description: "赠予喜爱阅读的 NPC 可增加其好感度 +15。书中会浮现对方最渴望的知识。",
    statBonus: { charm: 2 },
    tags: "gift,favor",
    statRequirements: { charm: 12 },
    ownerId: "N-011",
    effectType: "tempFavor",
    tempFavorEffect: 15,
  },
];
