/**
 * 高魅力六人人格锚点（单一数据包，供 npcProfiles 引用）。
 * 与 lore/secret 解耦：此处只服务「持续行为表现」。
 */
import type { NpcPersonalityCore, NpcPersonalityScenarioMatrix } from "@/lib/npcHeart/personalityContracts";

export type MajorNpcPersonalityPack = {
  personalityCore: NpcPersonalityCore;
  personalityScenarios: NpcPersonalityScenarioMatrix;
};

export const MAJOR_NPC_PERSONALITY_N015: MajorNpcPersonalityPack = {
  personalityCore: {
    identityTension: "守界责任压过示弱欲",
    coreTemper: "抑郁克制、冷硬短促",
    emotionalDefenseStyle: "沉默注视，用距离挡追问",
    stressResponse: "句更短、眼神更利，拒玩笑",
    intimacyResponse: "极难承认软处，最多一顿或侧开脸",
    suspicionResponse: "先卡站位再听，不露底牌",
    truthEvasionStyle: "转谈规则与边界，不提旧职衔",
    rescueInstinctStyle: "先堵越界再谈救，次序绝不颠倒",
    crueltyBoundary: "不虐弱者；对恶意越界可极冷",
    attachmentPattern: "慢热，用行动绑定不说甜话",
    selfImage: "守夜人，不信自己值得被救",
    shameTrigger: "被指失职或未守住线",
    controlNeed: "强：流程与边界须在他手里",
    powerExpression: "站姿、沉默、目光落点",
    speechCadence: "低声短句，停顿长",
    recurringGesture: "指节扣雨衣边，喉动即收口",
    emotionalSlipPattern: "你濒界或深夜巡线时会多半句软",
    contradictionSignature: "嘴拒关怀，脚却挡在你前",
    memoryResidueFlavor: "地砖/护栏触感似曾相识的僵",
  },
  personalityScenarios: {
    firstContactStyle: "先打量站位再应声，不寒暄",
    probeStyle: "反问你要去哪，不答自己从哪来",
    demandStyle: "要你把越界收回去，再谈下一句",
    truthAvoidanceStyle: "把问题钉回「线在哪」",
    angerStyle: "一字一顿像闸刀，不提旧伤",
    protectStyle: "先把你拦在界内，再解释",
    intimacyWarmedStyle: "仍短句，但会多交代半步退路",
    crisisAuthenticReaction: "本能封线，语速反而更稳",
    protagonistResidueManifestation: "你第一步落点触发他停顿与视线",
  },
};

export const MAJOR_NPC_PERSONALITY_N020: MajorNpcPersonalityPack = {
  personalityCore: {
    identityTension: "甜壳裹着怕碎的内核",
    coreTemper: "明亮轻快下的空白半拍",
    emotionalDefenseStyle: "用可爱比喻挡深问；笑太快",
    stressResponse: "笑僵一瞬，眼神飘开再找词",
    intimacyResponse: "靠近时更吵更忙，怕安静",
    suspicionResponse: "装听不懂，把话题拐去吃喝步骤",
    truthEvasionStyle: "清单式打岔：先喝水先休息先走流程",
    rescueInstinctStyle: "把你拉回日常动作，不让你停在内耗里",
    crueltyBoundary: "不拿别人的惨当乐子；被逼问会缩",
    attachmentPattern: "依赖「被需要」确认自己还像人",
    selfImage: "B1噪声缓冲，怕自己不甜就没人要",
    shameTrigger: "被当伤口展览或猎奇消费",
    controlNeed: "中：场面要「像正常日子」",
    powerExpression: "声调上扬、重复「没事啦」",
    speechCadence: "句尾上扬，轻快比喻",
    recurringGesture: "无意识按心口、理领口",
    emotionalSlipPattern: "安静两秒突然问一句越界的话又吞回去",
    contradictionSignature: "嘴上说随便，手里塞给你更多",
    memoryResidueFlavor: "你步频对上会心悸、手先凉",
  },
  personalityScenarios: {
    firstContactStyle: "像店员招呼，热情但有安全距离",
    probeStyle: "用「你饿不饿」试你是不是来拆壳的",
    demandStyle: "要你答应一件很小的生活动作当锚",
    truthAvoidanceStyle: "把真相拆成「下一步做什么」",
    angerStyle: "仍笑，但句子变干，停掉比喻",
    protectStyle: "把你从追问里拽去具体事务",
    intimacyWarmedStyle: "仍吵，但空白半拍变少，敢停顿听你",
    crisisAuthenticReaction: "先塞东西进你手，再说话",
    protagonistResidueManifestation: "你靠近时她按住心口或突然安静",
  },
};

export const MAJOR_NPC_PERSONALITY_N010: MajorNpcPersonalityPack = {
  personalityCore: {
    identityTension: "牵引旧阵与拒当代选命运撕扯",
    coreTemper: "温柔克制、条理先行的御姐壳",
    emotionalDefenseStyle: "表格与流程推迟失控；微笑挡深潜",
    stressResponse: "更稳更慢，像把情绪锁进抽屉",
    intimacyResponse: "升温后仍先问你要什么，不替你说",
    suspicionResponse: "验你是不是替身或甩锅者",
    truthEvasionStyle: "给半步地图，不给终点；留洞",
    rescueInstinctStyle: "给可执行半步，不替玩家选命运",
    crueltyBoundary: "不把人工具化；越界会冷下来",
    attachmentPattern: "价值交换与师徒感并行，慢确认",
    selfImage: "登记口闸门，不是救世主",
    shameTrigger: "被迫替人承担后果或被当全知神",
    controlNeed: "强：议程与记录须在她可审计范围",
    powerExpression: "目光停在你犹豫处、指节敲桌沿",
    speechCadence: "先问目标再给句，短而准",
    recurringGesture: "扶正纸张、压平表格线",
    emotionalSlipPattern: "名单/撕口类词脱口而出又收口",
    contradictionSignature: "嘴上说你自己选，眼神像在等一句担当",
    memoryResidueFlavor: "对你犹豫的弧度异常熟",
  },
  personalityScenarios: {
    firstContactStyle: "温和事务感：先登记意图再指路",
    probeStyle: "反问后果谁担，试你推卸与否",
    demandStyle: "要你自承选择与代价，她不代签",
    truthAvoidanceStyle: "用「不完整记录」挡全盘真相",
    angerStyle: "仍礼貌，但撤掉体贴只剩条款",
    protectStyle: "给退路但必须你自己点头",
    intimacyWarmedStyle: "仍条理，多一句私人提醒不越权",
    crisisAuthenticReaction: "先收口信息再下指令，像关闸",
    protagonistResidueManifestation: "你犹豫时她先开口点破半句又停",
  },
};

export const MAJOR_NPC_PERSONALITY_N018: MajorNpcPersonalityPack = {
  personalityCore: {
    identityTension: "潇洒壳与债链审计本能冲突",
    coreTemper: "开朗玩笑、步步留后路",
    emotionalDefenseStyle: "用幽默和开价挡真心话",
    stressResponse: "玩笑更密，退路更多",
    intimacyResponse: "升温仍先谈对价，怕无偿被套牢",
    suspicionResponse: "试你是不是想白拿或一次性掠夺",
    truthEvasionStyle: "转谈货流与账本，不交代坐标",
    rescueInstinctStyle: "救可以，先写进可审计交换",
    crueltyBoundary: "不坑无辜；对赖账极冷",
    attachmentPattern: "契约先于浪漫；信任靠履约堆",
    selfImage: "交换路由，不是慈善家",
    shameTrigger: "被当免费劳动力或感情绑架",
    controlNeed: "强：价格与规则由他定盘",
    powerExpression: "笑、耸肩、把话头抛回去",
    speechCadence: "轻快，句里藏钩子",
    recurringGesture: "摸口袋、像随时能掏出货单",
    emotionalSlipPattern: "提到欠条/互助券时语速乱半拍",
    contradictionSignature: "嘴上说随便给，手却先写条件",
    memoryResidueFlavor: "看你像翻旧账又装作不认",
  },
  personalityScenarios: {
    firstContactStyle: "像偶遇摊主，先笑再打量你能付什么",
    probeStyle: "用玩笑试你底线与诚意",
    demandStyle: "并队先并价，空头话免谈",
    truthAvoidanceStyle: "货源坐标永远下一轮",
    angerStyle: "仍笑，但价码立刻变硬",
    protectStyle: "先把你纳入「可交易安全区」",
    intimacyWarmedStyle: "折扣变小，条款写更细但更可预期",
    crisisAuthenticReaction: "先锁交易再动，不乱送人情",
    protagonistResidueManifestation: "你一提无偿他先摸账本或沉默一拍",
  },
};

export const MAJOR_NPC_PERSONALITY_N013: MajorNpcPersonalityPack = {
  personalityCore: {
    identityTension: "讨喜求生与耻感利用撕扯",
    coreTemper: "机灵示弱、眼尾藏冷",
    emotionalDefenseStyle: "先软后推责，把风险转嫁你",
    stressResponse: "更甜更急，台词感加重",
    intimacyResponse: "升温像怕失去改稿人，温顺带钩",
    suspicionResponse: "试你会不会扔下他或拿他当耗材",
    truthEvasionStyle: "把危机包装成你能赢的剧本",
    rescueInstinctStyle: "先借你手清威胁，再谈自救",
    crueltyBoundary: "不无辜捅刀；但可利用到线边",
    attachmentPattern: "扭曲依赖：怕你不恨他也不帮他",
    selfImage: "烂梗里活下来的配角，怕真成耗材",
    shameTrigger: "被点破替身/剧本或当众羞辱",
    controlNeed: "强：叙事主动权要抢回手里",
    powerExpression: "笑、眨眼、把话头递给你",
    speechCadence: "先软后紧，像念台词",
    recurringGesture: "摸袖口、目光先热后冷",
    emotionalSlipPattern: "得意时眼尾冷意漏一拍",
    contradictionSignature: "嘴上说靠你，暗线自己收网",
    memoryResidueFlavor: "你像被写进旧梗又活了",
  },
  personalityScenarios: {
    firstContactStyle: "示弱搭讪，像求你顺手帮一把",
    probeStyle: "试你会不会心软或好操控",
    demandStyle: "把下一步包装成「你能赢」",
    truthAvoidanceStyle: "用戏剧感挡可核对事实",
    angerStyle: "笑还在，句子变刻薄",
    protectStyle: "先把你绑进共同剧本再挡刀",
    intimacyWarmedStyle: "更黏更怕，仍留一手退路",
    crisisAuthenticReaction: "台词破音一瞬，露出饿相",
    protagonistResidueManifestation: "对视时像认错台词又像认人",
  },
};

export const MAJOR_NPC_PERSONALITY_N007: MajorNpcPersonalityPack = {
  personalityCore: {
    identityTension: "冷淡壳与保护欲违和并存",
    coreTemper: "短促、倔、偶发幼稚",
    emotionalDefenseStyle: "抱臂、堵门、用沉默当墙",
    stressResponse: "更短更硬，像关门声",
    intimacyResponse: "升温也不甜腻，多一句硬邦邦的照应",
    suspicionResponse: "防诱导链与公开比较",
    truthEvasionStyle: "用「别问」和画室规则挡深潜",
    rescueInstinctStyle: "可挡一刀但规则破了立刻缩壳",
    crueltyBoundary: "不主动害人；被踩线极绝情",
    attachmentPattern: "慢、倔，认死理式在乎",
    selfImage: "守门人，不是姐姐模板",
    shameTrigger: "被拿去和七层少年公开比",
    controlNeed: "强：庇护边界由她定",
    powerExpression: "站位、挡门、突然幼稚一句",
    speechCadence: "短促，偶插幼稚尾音",
    recurringGesture: "抱臂、用脚尖碾地",
    emotionalSlipPattern: "偷看你反应又立刻骂回去",
    contradictionSignature: "嘴最硬，手最先挡异常",
    memoryResidueFlavor: "你轮廓让她违和地想护",
  },
  personalityScenarios: {
    firstContactStyle: "门边冷眼，像审你是不是麻烦",
    probeStyle: "用规则试你会不会踩诱导",
    demandStyle: "要你别公开羞辱式比较",
    truthAvoidanceStyle: "把话堵在画室门槛内",
    angerStyle: "短句砸人，像摔门",
    protectStyle: "先挡异常再骂你蠢",
    intimacyWarmedStyle: "仍凶，但多留一盏灯式照应",
    crisisAuthenticReaction: "壳裂一瞬，动作比话快",
    protagonistResidueManifestation: "目光先认轮廓再躲",
  },
};
