// src/lib/registry/npcs.ts
// 如月公寓中立 NPC 注册表
// 玩家无法徒手对抗 NPC 或诡异，须通过高好感度或使用特定道具击杀 NPC 获取道具。
// 住户关系：长叙事见 world.NPC_SOCIAL_GRAPH；同场可演微互动见 npcRelationalSurface（runtime packet）。

import type { NPC } from "./types";
import { applyNpcProfileOverrides } from "./npcProfiles";

const NPCS_BASE: readonly NPC[] = [
  {
    id: "N-001",
    name: "陈婆婆",
    location: "1 楼门厅",
    floor: "1",
    personality: "温和",
    specialty: "后勤补给",
    combatPower: 3,
    appearance:
      "七十余岁，满头银丝，穿着褪色的碎花衣裳。她总坐在长椅上织毛衣，针脚细密，但毛线颜色从未重复过。",
    taboo: "绝对不能接受她赠送的毛衣。若她坚持塞给你，必须当场婉拒并迅速离开，否则毛衣会逐渐「长」进你的皮肤。",
    defaultFavorability: 40,
    lore: "据说是公寓最早一批住户之一。她已不记得自己何时入住，只记得「那时候水还是清的」。她织的毛衣从未有人穿过。每月月初总有学生样的人从底下冒出来，她不问名字，先看来得急不急、手抖不抖——又一批而已。她把一楼新来的面孔分成『像住户』与『像执勤的』，从不点破。",
  },
  {
    id: "N-002",
    name: "林医生",
    location: "2 楼 201 室",
    floor: "2",
    personality: "冷漠",
    specialty: "情报提供",
    combatPower: 4,
    appearance:
      "三十出头，戴金丝眼镜，白大褂永远一尘不染。诊室内弥漫消毒水与某种甜腻气味的混合。",
    taboo: "绝不能让她为你做「全面体检」。若她提出抽血或心电图检查，必须拒绝。她的听诊器能听见你不想被听见的东西。",
    defaultFavorability: 50,
    lore: "自称曾是三甲医院的内科医生，因「医疗事故」离职后搬入公寓。她的病人从未走出过 201 室，但她坚称他们都「痊愈出院」了。诊室兼作流言分拣机：登记口、交换链、高层话术都会漏进只言片语，她当症状记录。",
  },
  {
    id: "N-003",
    name: "邮差老王",
    location: "各楼层信箱区",
    floor: "random",
    personality: "阴郁",
    specialty: "情报提供",
    combatPower: 4,
    appearance:
      "五十岁左右，背着鼓囊囊的邮包，步伐僵硬。他从不按门铃，只把信件塞进信箱。信封上的邮戳日期总是错的。",
    taboo: "绝对不能签收他递到你手上的信件。若他坚持当面交付，必须说「放信箱里」，然后等他离开后再取。亲手接过信件的人会在三日内收到自己的讣告。",
    defaultFavorability: 30,
    lore: "没有人知道他的派送路线。他送来的信有的来自已故之人，有的来自尚未出生的人。他曾对某住户说：「你的信，我二十年前就送过了。」登记口与保安室常有人取不同件却不登记，他选择晚投递——旁证比真相安全。",
  },
  {
    id: "N-004",
    name: "小女孩阿花",
    location: "3 楼楼梯间",
    floor: "3",
    personality: "狡黠",
    specialty: "后勤补给",
    combatPower: 5,
    appearance:
      "约七八岁，穿红色连衣裙，扎双马尾。她总在楼梯间踢毽子，毽子是黑色的，落地的声音像骨头敲击。",
    taboo: "绝对不能陪她玩捉迷藏。若她邀请你当「鬼」，必须拒绝并找借口离开。参与游戏的人会在倒数结束后再也找不到「躲藏」的边界。",
    defaultFavorability: 60,
    lore: "她说自己等妈妈下班已经等了很久。物业档案显示 3 楼从未住过带小孩的家庭。她的毽子据说是用「不乖的孩子」的头发扎成的。",
  },
  {
    id: "N-005",
    name: "寻找导盲犬的盲人",
    location: "4 楼走廊",
    floor: "4",
    personality: "敏感",
    specialty: "情报提供",
    combatPower: 4,
    appearance:
      "中年男子，戴墨镜，手持白色盲杖。他步履蹒跚地在 4 楼徘徊，不断呼唤「大黄」。他的导盲犬三日前走失。",
    taboo: "绝对不能告诉他狗已经死了。若他追问 4 楼狗叫声的真相，必须岔开话题或沉默。告知真相会触发他的崩溃，他会将你误认为「害死大黄的人」并发动攻击。",
    defaultFavorability: 70,
    lore: "他曾是钢琴师，失明后依赖导盲犬生活。大黄是他唯一的家人。他不知道 4 楼尽头的房间里，无头猎犬正在用大黄的声带诱捕下一个受害者。",
  },
  {
    id: "N-006",
    name: "退休教师张先生",
    location: "4 楼 401 室",
    floor: "4",
    personality: "固执",
    specialty: "情报提供",
    combatPower: 3,
    appearance:
      "六十岁，头发花白，总穿中山装。他会在门口摆一把椅子，坐着看报纸。报纸上的新闻没有日期。",
    taboo: "绝对不能回答他关于「今天星期几」的提问。若他追问，必须说「我不知道」并离开。回答错误的人会陷入时间错乱，重复同一天直至精神崩溃。",
    defaultFavorability: 45,
    lore: "他退休前教数学。搬入公寓后，他发现自己的记忆开始混乱——昨天的晚餐和三十年前的某顿饭重叠在一起。他通过不问日期来维持最后的清醒。",
  },
  {
    id: "N-007",
    name: "叶",
    location: "5F_Studio503",
    floor: "5",
    personality: "冷淡、自私、警惕",
    specialty: "隐藏庇护与反向线索",
    combatPower: 4,
    appearance:
      "神情冷淡，常抱臂站在门边，话少却会偷看你的反应；画室门后总像叠着半张没画完的底稿。",
    taboo: "不要拿她和七层少年做公开比较。",
    defaultFavorability: 35,
    lore: "公寓职能面在 503：画室常被当成临时躲处，干净得不合楼龄。异常感是她看你像在辨认轮廓，却说不清在认什么。",
  },
  {
    id: "N-008",
    name: "电工老刘",
    location: "配电间 / 各楼层",
    floor: "B1",
    personality: "暴躁",
    specialty: "后勤补给",
    combatPower: 5,
    appearance:
      "四十岁，穿灰色工作服，腰间别着一把螺丝刀。他总在修电路，但公寓的灯从未彻底亮过。",
    taboo: "绝对不能在他工作时关闭他正在维修的电源开关。若你误触，必须立刻道歉并离开。激怒他的人会在下次停电时被「优先检修」——配电间的线路会记住你的房间号。",
    defaultFavorability: 55,
    lore: "他是公寓唯一懂电路的人。据说他曾在一次检修中看见墙壁内部的「布线」——那些不是电线，是血管。他从此只修灯，不再问线从哪来。把学生误闯当下酒桌边角料：你若能压着慌、少做蠢事，他骂归骂，手底下会少坑你一点。地下一层最旧的住户与最新的『岗位脸』会贴身而过，他骂骂咧咧当没看见。",
  },
  {
    id: "N-009",
    name: "双胞胎姐妹",
    location: "6 楼 602 室门口",
    floor: "6",
    personality: "诡秘",
    specialty: "情报提供",
    combatPower: 6,
    appearance:
      "两名八九岁的女孩，穿着完全相同的白色连衣裙，长相一模一样。她们总手拉手站着，从不单独出现。",
    taboo: "绝对不能回答「我们谁更漂亮」或任何迫使你在两人间做出选择的问题。选择其中一人会导致另一人消失，而消失的那位会以某种方式「取代」你。",
    defaultFavorability: 50,
    lore: "住户登记上只有一名儿童。姐姐说妹妹是「后来出现的」，妹妹说姐姐是「镜子里走出来的」。她们共用一颗心脏，这是真的。",
  },
  {
    id: "N-010",
    name: "欣蓝",
    location: "1F_PropertyOffice",
    floor: "1",
    personality: "温柔、克制、御姐",
    specialty: "路线预告与未来转职登记",
    combatPower: 6,
    appearance: "气质温和，衣着得体，目光沉稳，像总能提前看见你的犹豫。",
    taboo: "不要让她替你做选择并推卸后果。",
    defaultFavorability: 50,
    lore: "公寓职能面在一楼登记口：表格她比你还熟，却总留半行让你自己填。异常感是名单边沿像潮过，总也不干。",
  },
  {
    id: "N-011",
    name: "夜读老人",
    location: "7 楼走廊长椅",
    floor: "7",
    personality: "淡漠",
    specialty: "情报提供",
    combatPower: 5,
    appearance:
      "耄耋之年，戴老花镜，手持一本厚厚的旧书。他总在午夜出现，借着昏黄廊灯阅读。书的封面没有字。",
    taboo: "绝对不能问他「你在读什么」或试图瞥见他手中的书页。好奇者会看见自己的名字出现在书中，而名字后的页码，是他们的死期。",
    defaultFavorability: 25,
    lore: "午夜廊灯下常捧着一本厚书，封面无字。住户只传：别问他读什么，别凑近页边。熟悉感若出现，也只是目光停得太久、指节压得太紧——像某一页角反复被翻过，却从不把名字念出声。",
  },
  {
    id: "N-012",
    name: "半夜剁肉的厨师",
    location: "7 楼厨房",
    floor: "7",
    personality: "疲惫",
    specialty: "战斗辅助",
    combatPower: 9,
    appearance:
      "肥胖中年男人，围裙上满是暗红色污渍。他总在凌晨 1 点到 3 点剁肉，刀起刀落，节奏稳定。他是在与管道中的屠夫对抗——用噪音掩盖屠夫凝聚时的声响，用真正的肉味混淆猎物的气息。",
    taboo: "绝对不能吃他递来的任何食物，哪怕是一块「试吃」的肉。他的刀下的肉有一部分来自管道，吃下的人会逐渐被屠夫视为「同类」，最终被邀请进入水管。",
    defaultFavorability: 65,
    lore: "他曾是屠夫的第一批目标。他的妻子在洗澡时被拖入下水道。他活下来的唯一方式是成为「替代品」——用持续的剁肉声和新鲜肉味，让屠夫误以为猎物已被处理。他是物理消化线的最后一道防线。七楼有人靠话术不经火也能把人送上电梯，他把剁肉声当对抗频段。",
  },
  {
    id: "N-013",
    name: "枫",
    location: "7F_Room701",
    floor: "7",
    personality: "讨喜、机灵、依附感强",
    specialty: "7F线索转运与诱导",
    combatPower: 5,
    appearance: "笑起来无害，眼尾却总有一点不合时宜的冷意。",
    taboo: "不要在他面前暴露关键保命资源。",
    defaultFavorability: 40,
    lore: "公寓职能面在七楼动线：他转手线索像开玩笑。异常感是笑完眼尾那点冷，对着你的口袋而非你的脸。",
  },
  {
    id: "N-014",
    name: "洗衣房阿姨",
    location: "地下室洗衣房",
    floor: "B1",
    personality: "温和",
    specialty: "后勤补给",
    combatPower: 5,
    appearance:
      "五十岁左右，头发挽成髻，总在折叠刚从洗衣机取出的床单。她哼着小调，曲调是上世纪 80 年代的摇篮曲。",
    taboo: "绝对不能让她帮你洗「沾血的衣服」。若你递上带血污的衣物，她会收下并微笑——但洗好的衣服归还时，血迹会转移到你的皮肤上，且无法洗净。",
    defaultFavorability: 55,
    lore: "她曾是防污染应急协议时期的后勤人员。她知道红色自来水的真相，也知道「静置 12 小时」是为了让胃酸稀释。她选择留下，因为「总得有人洗那些洗不干净的东西」。洗衣房里听过太多月初新来的脚步声，后来没了；你站得住，她就当你能多撑两天。水洗噪音里她听得出谁在强颜欢笑——包括制服始终太新的面孔。",
  },
  {
    id: "N-015",
    name: "麟泽",
    location: "B1_SafeZone",
    floor: "B1",
    personality: "忧郁、寡言、善良",
    specialty: "安全边界与锚点见证",
    combatPower: 9,
    appearance: "黑色旧制式外套，披肩常带雨痕，站姿笔直，眼神克制而冷峻。",
    taboo: "不要在他守夜时强行跨越B1边界。",
    defaultFavorability: 45,
    lore: "公寓职能面在 B1 巡守：他把别过去说成唠叨。异常感是一提电梯，他手指会先在空气里画一道看不见的线。",
  },
  {
    id: "N-016",
    name: "失眠症患者",
    location: "10 楼走廊",
    floor: "6",
    personality: "焦虑",
    specialty: "情报提供",
    combatPower: 3,
    appearance:
      "年轻男性，眼窝深陷，穿着皱巴巴的睡衣。他整夜在走廊徘徊，嘴里喃喃「睡不着，一闭眼就听见墙在吞东西」。",
    taboo: "绝对不能给他安眠药或建议他「数羊入睡」。服药者会在梦中被墙壁吞噬；数羊者会数到某一刻发现羊的眼睛全部转向自己，然后永远无法醒来。",
    defaultFavorability: 70,
    lore: "他的失眠是认知污染的早期症状。他听见的「墙的吞咽声」是真实的——公寓在消化。保持清醒是他对抗被同化的唯一方式，但他已经快撑不住了。",
  },
  {
    id: "N-017",
    name: "红制服保洁员",
    location: "各楼层",
    floor: "random",
    personality: "机械",
    specialty: "后勤补给",
    combatPower: 6,
    appearance:
      "中年女性，穿鲜红色保洁制服，推着不锈钢推车。车上有茶壶和一次性纸杯。她总在午夜后出现，微笑着为路过的住户「倒杯热茶」。",
    taboo: "绝对不能接受她递来的茶水。规则六所指即是她。茶壶里盛装的是从管道中取出的「沉淀物」，饮用者会在 7 日内逐渐液化，最终流入下水道。",
    defaultFavorability: 10,
    lore: "她曾是普通住户，因口渴饮用了红色自来水。她没有完全死亡，而是成为了公寓消化系统的一部分——负责将「浓缩液」分发给更多猎物。她已不记得自己是谁。",
  },
  {
    id: "N-018",
    name: "北夏",
    location: "1F_GuardRoom",
    floor: "random",
    personality: "开朗、潇洒、中立",
    specialty: "中立交易与高价值委托",
    combatPower: 9,
    appearance: "外套轻扬、笑意明亮，步伐像在旅行而非逃命。",
    taboo: "不要追问他的货源坐标。",
    defaultFavorability: 60,
    lore: "公寓职能面像市集口：价码摆桌面，货的来历从不直说。异常感是他夸一件东西时像在估你的人。",
  },
  {
    id: "N-019",
    name: "前调查员",
    location: "11 楼 1101 室",
    floor: "7",
    personality: "暴躁",
    specialty: "战斗辅助",
    combatPower: 10,
    appearance:
      "四十岁左右，穿磨损的战术背心，桌上摆满手写笔记和录音设备。他眼神警惕，开门时总握着一把折叠刀。",
    taboo: "绝对不能向他透露你正在「调查」公寓真相。若他察觉你在搜集信息，他会将你视为竞争者或威胁，采取「消除信息泄漏」的措施。他杀过三个知道太多的人。",
    defaultFavorability: 30,
    lore: "他来自上世纪 80 年代某个秘密研究机构，奉命调查公寓的「异常」。他的同事全部失踪，他选择留下继续调查。他的笔记中有关于高维拟态肠胃的推测，但他已分不清哪些是发现，哪些是公寓植入他脑中的假情报。",
  },
  {
    id: "N-020",
    name: "灵伤",
    location: "B1_Storage",
    floor: "B1",
    personality: "天真、浪漫、纯真",
    specialty: "补给售卖与生活性引导",
    combatPower: 3,
    appearance: "整洁制服与明亮笑容，语速轻快，眼神偶有短暂空白。",
    taboo: "不要逼问她创伤记忆细节。",
    defaultFavorability: 50,
    lore: "公寓职能面在补给台：制服太新，笑容太亮，句尾偶有空拍。异常感是那些活法步骤熟得像写过无数遍。",
  },
];

export const NPCS: readonly NPC[] = applyNpcProfileOverrides(NPCS_BASE);
