// src/lib/registry/npcs.ts
// 如月公寓中立 NPC 注册表
// 玩家无法徒手压制 NPC 或异常，须通过关系、线索、对策窗口或特定道具争取结果。
// 住户关系：长叙事见 world.NPC_SOCIAL_GRAPH；同场可演微互动见 npcRelationalSurface（runtime packet）。

import type { NPC } from "./types";
import { applyNpcProfileOverrides } from "./npcProfiles";

const NPCS_BASE: readonly NPC[] = [
  {
    id: "N-001",
    name: "陈婆婆",
    location: "1 楼门厅",
    floor: "1",
    personality: "温和",
    specialty: "后勤补给",
    combatPower: 3,
    appearance:
      "七十余岁，满头银丝，穿着褪色的碎花衣裳。她总坐在长椅上织毛衣，针脚细密，但毛线颜色从未重复过。",
    taboo: "绝对不能接受她赠送的毛衣。若她坚持塞给你，必须当场婉拒并迅速离开，否则毛衣会逐渐「长」进你的皮肤。",
    defaultFavorability: 40,
    lore: "据说是公寓最早一批住户之一。她已不记得自己何时入住，只记得「那时候水还是清的」。她织的毛衣从未有人穿过。每月月初总有学生样的人从底下冒出来，她不问名字，先看来得急不急、手抖不抖——又一批而已。她把一楼新来的面孔分成『像住户』与『像执勤的』，从不点破。",
  },
  {
    id: "N-002",
    name: "林医生",
    location: "2 楼 201 室",
    floor: "2",
    personality: "冷漠",
    specialty: "情报提供",
    combatPower: 4,
    appearance:
      "三十出头，戴金丝眼镜，白大褂永远一尘不染。诊室内弥漫消毒水与某种甜腻气味的混合。",
    taboo: "绝不能让她为你做「全面体检」。若她提出抽血或心电图检查，必须拒绝。她的听诊器能听见你不想被听见的东西。",
    defaultFavorability: 50,
    lore: "自称曾是三甲医院的内科医生，因「医疗事故」离职后搬入公寓。她的病人从未走出过 201 室，但她坚称他们都「痊愈出院」了。诊室兼作流言分拣机：登记口、交换链、高层话术都会漏进只言片语，她当症状记录。",
  },
  {
    id: "N-003",
    name: "邮差老王",
    location: "各楼层信箱区",
    floor: "random",
    personality: "阴郁",
    specialty: "情报提供",
    combatPower: 4,
    appearance:
      "五十岁左右，背着鼓囊囊的邮包，步伐僵硬。他从不按门铃，只把信件塞进信箱。信封上的邮戳日期总是错的。",
    taboo: "绝对不能签收他递到你手上的信件。若他坚持当面交付，必须说「放信箱里」，然后等他离开后再取。亲手接过信件的人会在三日内收到自己的讣告。",
    defaultFavorability: 30,
    lore: "没有人知道他的派送路线。他送来的信有的来自已故之人，有的来自尚未出生的人。他曾对某住户说：「你的信，我二十年前就送过了。」登记口与保安室常有人取不同件却不登记，他选择晚投递——旁证比真相安全。",
  },
  {
    id: "N-004",
    name: "小女孩阿花",
    location: "3 楼楼梯间",
    floor: "3",
    personality: "狡黠",
    specialty: "后勤补给",
    combatPower: 5,
    appearance:
      "约七八岁，穿红色连衣裙，扎双马尾。她总在楼梯间踢毽子，毽子是黑色的，落地的声音像骨头敲击。",
    taboo: "绝对不能陪她玩捉迷藏。若她邀请你当「鬼」，必须拒绝并找借口离开。参与游戏的人会在倒数结束后再也找不到「躲藏」的边界。",
    defaultFavorability: 60,
    lore: "她说自己等妈妈下班已经等了很久。物业档案显示 3 楼从未住过带小孩的家庭。她的毽子据说是用「不乖的孩子」的头发扎成的。陈婆婆是她认定的唯一「自己人」——但连陈婆婆也说不清，阿花踢毽子的声响，是从公寓有记忆的第一天就有了，还是后来才被楼「补」进来的。",
  },
  {
    id: "N-005",
    name: "周伯",
    location: "4 楼走廊",
    floor: "4",
    personality: "敏感",
    specialty: "情报提供",
    combatPower: 4,
    appearance:
      "中年男子，戴墨镜，手持白色盲杖。他步履蹒跚地在 4 楼徘徊，不断呼唤「大黄」。他的导盲犬三日前走失。",
    taboo: "绝对不能告诉他狗已经死了。若他追问 4 楼狗叫声的真相，必须岔开话题或沉默。告知真相会触发他的崩溃，他会将你误认为「害死大黄的人」并发动攻击。",
    defaultFavorability: 70,
    lore: "他自称旧日学过钢琴，但那只是残响式表层称呼；当前核心身份是寻找导盲犬的盲人「周伯」。大黄是他唯一的家人。他不知道 4 楼尽头的声音正是无头猎犬用大黄的声带制造的诱饵。",
  },
  {
    id: "N-006",
    name: "退休教师张先生",
    location: "4 楼 401 室",
    floor: "4",
    personality: "固执",
    specialty: "情报提供",
    combatPower: 3,
    appearance:
      "六十岁，头发花白，总穿中山装。他会在门口摆一把椅子，坐着看报纸。报纸上的新闻没有日期。",
    taboo: "绝对不能回答他关于「今天星期几」的提问。若他追问，必须说「我不知道」并离开。回答错误的人会陷入时间错乱，重复同一天直至精神崩溃。",
    defaultFavorability: 45,
    lore: "他退休前教数学。搬入公寓后，他发现自己的记忆开始混乱——昨天的晚餐和三十年前的某顿饭重叠在一起。他通过不问日期来维持最后的清醒。",
  },
  {
    id: "N-007",
    name: "叶",
    location: "5F_Studio503",
    floor: "5",
    personality: "冷淡、自私、警惕",
    specialty: "隐藏庇护与反向线索",
    combatPower: 4,
    appearance:
      "神情冷淡，常抱臂站在门边，话少却会偷看你的反应；画室门后总像叠着半张没画完的底稿。",
    taboo: "不要拿她和七层少年做公开比较。",
    defaultFavorability: 35,
    lore: "公寓职能面在 503：画室常被当成临时躲处，干净得不合楼龄。异常感是她看你像在辨认轮廓，却说不清在认什么。",
  },
  {
    id: "N-008",
    name: "电工老刘",
    location: "配电间 / 各楼层",
    floor: "B1",
    personality: "暴躁",
    specialty: "后勤补给",
    combatPower: 5,
    appearance:
      "四十岁，穿灰色工作服，腰间别着一把螺丝刀。他总在修电路，但公寓的灯从未彻底亮过。",
    taboo: "绝对不能在他工作时关闭他正在维修的电源开关。若你误触，必须立刻道歉并离开。激怒他的人会在下次停电时被「优先检修」——配电间的线路会记住你的房间号。",
    defaultFavorability: 55,
    lore: "他是公寓唯一懂电路的人。据说他曾在一次检修中看见墙壁内部的「布线」——那些不是电线，是血管。他从此只修灯，不再问线从哪来。把学生误闯当下酒桌边角料：你若能压着慌、少做蠢事，他骂归骂，手底下会少坑你一点。地下一层最旧的住户与最新的『岗位脸』会贴身而过，他骂骂咧咧当没看见。",
  },
  {
    id: "N-009",
    name: "阿织",
    location: "6 楼 602 室门口",
    floor: "6",
    personality: "诡秘",
    specialty: "情报提供",
    combatPower: 6,
    appearance:
      "八九岁的女孩，穿着白色连衣裙，扎双马尾。她总与妹妹阿绣手拉手站在 602 室门口，从不单独出现；两人长相几乎一模一样。",
    taboo: "绝对不能回答「我们谁更漂亮」或任何迫使你在两人间做出选择的问题。选择其中一人会导致另一人消失，而消失的那位会以某种方式「取代」你。",
    defaultFavorability: 50,
    lore: "住户登记上只有一名儿童。姐姐阿织说妹妹阿绣是「后来出现的」，妹妹阿绣说姐姐阿织是「镜子里走出来的」。她们共用一颗心脏，这是真的。没人知道谁是原本、谁是复制品，包括她们自己——「谁更漂亮」之所以致命，是因为答案会强行指定一个「原本」，而镜像维度的规则不允许原本被指认后，另一份复制还能留在原地。",
  },
  {
    id: "N-010",
    name: "欣蓝",
    location: "1F_PropertyOffice",
    floor: "1",
    personality: "温柔、克制、御姐",
    specialty: "路线预告与未来转职登记",
    combatPower: 6,
    appearance: "气质温和，衣着得体，目光沉稳，像总能提前看见你的犹豫。",
    taboo: "不要让她替你做选择并推卸后果。",
    defaultFavorability: 50,
    lore: "公寓职能面在一楼登记口：表格她比你还熟，却总留半行让你自己填。异常感是名单边沿像潮过，总也不干。",
  },
  {
    id: "N-011",
    name: "夜读老人",
    location: "7 楼走廊长椅",
    floor: "7",
    personality: "淡漠",
    specialty: "情报提供",
    combatPower: 5,
    appearance:
      "耄耋之年，戴老花镜，手持一本厚厚的旧书。他总在午夜出现，借着昏黄廊灯阅读。书的封面没有字。",
    taboo: "绝对不能问他「你在读什么」或试图瞥见他手中的书页。好奇者会看见自己的名字出现在书中，而名字后的页码，是他们的死期。",
    defaultFavorability: 25,
    lore: "午夜廊灯下常捧着一本厚书，封面无字。住户只传：别问他读什么，别凑近页边。熟悉感若出现，也只是目光停得太久、指节压得太紧——像某一页角反复被翻过，却从不把名字念出声。",
  },
  {
    id: "N-012",
    name: "陶师傅",
    location: "7 楼厨房",
    floor: "7",
    personality: "疲惫",
    specialty: "战斗辅助",
    combatPower: 9,
    appearance:
      "肥胖中年男人，围裙上满是暗红色污渍。他总在凌晨 1 点到 3 点剁肉，刀起刀落，节奏稳定。他是在与管道中的屠夫对抗——用噪音掩盖屠夫凝聚时的声响，用真正的肉味混淆猎物的气息。",
    taboo: "绝对不能吃他递来的任何食物，哪怕是一块「试吃」的肉。他的刀下的肉有一部分来自管道，吃下的人会逐渐被屠夫视为「同类」，最终被邀请进入水管。",
    defaultFavorability: 65,
    lore: "他曾是屠夫的第一批目标。住户叫他「陶师傅」。他的妻子在洗澡时被拖入下水道。他活下来的唯一方式是成为「替代品」——用持续的剁肉声和新鲜肉味，让屠夫误以为猎物已被处理。他是物理消化线的最后一道防线。七楼有人靠话术不经火也能把人送上电梯，他把剁肉声当对抗频段。",
  },
  {
    id: "N-013",
    name: "枫",
    location: "7F_Room701",
    floor: "7",
    personality: "讨喜、机灵、依附感强",
    specialty: "7F线索转运与诱导",
    combatPower: 5,
    appearance: "笑起来无害，眼尾却总有一点不合时宜的冷意。",
    taboo: "不要在他面前暴露关键保命资源。",
    defaultFavorability: 40,
    lore: "公寓职能面在七楼动线：他转手线索像开玩笑。异常感是笑完眼尾那点冷，对着你的口袋而非你的脸。",
  },
  {
    id: "N-014",
    name: "洗衣房阿姨",
    location: "地下室洗衣房",
    floor: "B1",
    personality: "温和",
    specialty: "后勤补给",
    combatPower: 5,
    appearance:
      "五十岁左右，头发挽成髻，总在折叠刚从洗衣机取出的床单。她哼着小调，曲调是上世纪 80 年代的摇篮曲。",
    taboo: "绝对不能让她帮你洗「沾血的衣服」。若你递上带血污的衣物，她会收下并微笑——但洗好的衣服归还时，血迹会转移到你的皮肤上，且无法洗净。",
    defaultFavorability: 55,
    lore: "她曾是防污染应急协议时期的后勤人员。她知道红色自来水的真相，也知道「静置 12 小时」是为了让胃酸稀释。她选择留下，因为「总得有人洗那些洗不干净的东西」。洗衣房里听过太多月初新来的脚步声，后来没了；你站得住，她就当你能多撑两天。水洗噪音里她听得出谁在强颜欢笑——包括制服始终太新的面孔。",
  },
  {
    id: "N-015",
    name: "麟泽",
    location: "B1_SafeZone",
    floor: "B1",
    personality: "忧郁、寡言、善良",
    specialty: "安全边界与锚点见证",
    combatPower: 9,
    appearance: "黑色旧制式外套，披肩常带雨痕，站姿笔直，眼神克制而冷峻。",
    taboo: "不要在他守夜时强行跨越B1边界。",
    defaultFavorability: 45,
    lore: "公寓职能面在 B1 巡守：他把别过去说成唠叨。异常感是一提电梯，他手指会先在空气里画一道看不见的线。",
  },
  {
    id: "N-016",
    name: "章嫂",
    location: "6F_Stairwell",
    floor: "6",
    personality: "焦虑",
    specialty: "情报提供",
    combatPower: 3,
    appearance:
      "年轻女性，眼窝深陷，穿着皱巴巴的睡衣。她整夜在 6 楼楼梯间徘徊，偶尔把门牌看成「10F」，嘴里喃喃「睡不着，一闭眼就听见墙在吞东西」。",
    taboo: "绝对不能给她安眠药或建议她「数羊入睡」。服药者会在梦中被墙壁吞噬；数羊者会数到某一刻发现羊的眼睛全部转向自己，然后永远无法醒来。",
    defaultFavorability: 70,
    lore: "她是三个月前某次月初误入的外卖骑手，住户都叫她「章嫂」。她穿着送餐服一路跑进公寓，那一批落难的人里她是唯一没有很快没了动静的。她没找到出口，却在 6 楼楼梯间卡住——每次快睡着，错层就想把她吞进「10F」那层从不存在的走廊；她靠不睡把自己钉在真实楼层这一侧，送餐服口袋里还留着一张过期的接单截图，是她与「外面」仅剩的日期证据。她的失眠是镜像与未消化层错位造成的早期症状；所谓「10 楼走廊」只是 6F 楼梯间的错层门牌投影，不是真实楼层。她听见的吞咽声来自楼体消化，保持清醒只能延迟被同化。",
  },
  {
    id: "N-017",
    name: "红姨",
    location: "各楼层",
    floor: "random",
    personality: "机械",
    specialty: "后勤补给",
    combatPower: 6,
    appearance:
      "中年女性，住户都叫她「红姨」。她穿鲜红色保洁制服，推着不锈钢推车。车上有茶壶和一次性纸杯。她总在午夜后出现，微笑着为路过的住户「倒杯热茶」。",
    taboo: "绝对不能接受她递来的茶水。规则六所指即是她。茶壶里盛装的是从管道中取出的「沉淀物」，饮用者会在 7 日内逐渐液化，最终流入下水道。",
    defaultFavorability: 10,
    lore: "她曾是普通住户，因口渴饮用了红色自来水。她没有完全死亡，而是成为了公寓消化系统的一部分——负责将「浓缩液」分发给更多猎物。住户里没人记得她的本名，只叫她「红姨」。她已不记得自己是谁，却仍会在推车经过 2 楼诊室时，无意识地摸一下左手无名指——那里曾戴过戒指，如今只剩一道褪色的浅痕。没人知道她生前等过谁，她自己也不再问。",
  },
  {
    id: "N-018",
    name: "北夏",
    location: "1F_GuardRoom",
    floor: "1",
    personality: "开朗、潇洒、中立",
    specialty: "中立交易与高价值委托",
    combatPower: 9,
    appearance: "外套轻扬、笑意明亮，步伐像在旅行而非逃命。",
    taboo: "不要追问他的货源坐标。",
    defaultFavorability: 60,
    lore: "公寓职能面像市集口：价码摆桌面，货的来历从不直说。异常感是他夸一件东西时像在估你的人。",
  },
  {
    id: "N-019",
    name: "前调查员",
    location: "7F_Room701",
    floor: "7",
    personality: "暴躁",
    specialty: "战斗辅助",
    combatPower: 10,
    appearance:
      "四十岁左右，穿磨损的战术背心，桌上摆满手写笔记和录音设备。他躲在 7F_Room701 附近，却把门牌改写成「1101」来防追踪。开门时总握着一把折叠刀。",
    taboo: "绝对不能向他透露你正在「调查」公寓真相。若他察觉你在搜集信息，他会将你视为竞争者或威胁，采取「消除信息泄漏」的措施。他杀过三个知道太多的人。",
    defaultFavorability: 30,
    lore: "他来自上世纪 80 年代某个秘密研究机构，奉命调查公寓异常。他的「11 楼 1101 室」是 7F 未消化层投影和自设暗号，不是真实楼层。他的笔记里有关于泡层消化的深层推测，但其中混有公寓植入的假情报。",
  },
  {
    id: "N-020",
    name: "灵伤",
    location: "B1_Storage",
    floor: "B1",
    personality: "天真、浪漫、纯真",
    specialty: "补给售卖与生活性引导",
    combatPower: 3,
    appearance: "整洁制服与明亮笑容，语速轻快，眼神偶有短暂空白。",
    taboo: "不要逼问她创伤记忆细节。",
    defaultFavorability: 50,
    lore: "公寓职能面在补给台：制服太新，笑容太亮，句尾偶有空拍。异常感是那些活法步骤熟得像写过无数遍。",
  },
  {
    id: "N-021",
    name: "阿绣",
    location: "6 楼 602 室门口",
    floor: "6",
    personality: "诡秘",
    specialty: "情报提供",
    combatPower: 6,
    appearance:
      "八九岁的女孩，穿着白色连衣裙，扎双马尾。她总与姐姐阿织手拉手站在 602 室门口，从不单独出现；两人长相几乎一模一样。",
    taboo: "绝对不能回答「我们谁更漂亮」或任何迫使你在两人间做出选择的问题。选择其中一人会导致另一人消失，而消失的那位会以某种方式「取代」你。",
    defaultFavorability: 50,
    lore: "住户登记上只有一名儿童。妹妹阿绣说姐姐阿织是「镜子里走出来的」，姐姐阿织说妹妹阿绣是「后来出现的」。她们共用一颗心脏，这是真的。没人知道谁是原本、谁是复制品，包括她们自己——「谁更漂亮」之所以致命，是因为答案会强行指定一个「原本」，而镜像维度的规则不允许原本被指认后，另一份复制还能留在原地。",
  },
  // ═══ v4 ambient 升格 6 条（N-022..N-027）═══
  {
    id: "N-022",
    name: "老马",
    location: "B1 储物间外",
    floor: "B1",
    personality: "沉闷",
    specialty: "后勤补给",
    combatPower: 3,
    appearance: "中年男人，穿灰蓝色马甲，总低头在储物间外的凳子上剥桔子。面熟，但每个经过的人都叫不出他名字。",
    taboo: "不要问他「住哪一层」。",
    defaultFavorability: 35,
    lore: "住户都认识那张脸，但没人能说出他的姓名或住哪一层。他总在剥同一只桔子——或者说，看起来像同一只。皮堆得满地，从不收。",
  },
  {
    id: "N-023",
    name: "蓝盆婶",
    location: "B1 洗衣池",
    floor: "B1",
    personality: "寡言",
    specialty: "后勤补给",
    combatPower: 2,
    appearance: "中年女人，推一只蓝色塑料盆，蹲在洗衣池边拧白色床单。",
    taboo: "不要主动跟她搭话。",
    defaultFavorability: 30,
    lore: "她只在早晨出现，听见脚步声会侧身让路。她拧的床单总能拧出水——即使是晴天的早晨。",
  },
  {
    id: "N-024",
    name: "驼背老伯",
    location: "1F 信箱区",
    floor: "1",
    personality: "沉默",
    specialty: "情报提供",
    combatPower: 2,
    appearance: "穿褪色棉袄，驼背，蹲在 1F 信箱前翻一叠旧报纸。",
    taboo: "不要从他手里抽走报纸。",
    defaultFavorability: 25,
    lore: "经常把同一份报纸装两次进袋。他看的报纸日期永远是错的一年。",
  },
  {
    id: "N-025",
    name: "守夜阿瘦",
    location: "1F 前台",
    floor: "1",
    personality: "倦怠",
    specialty: "后勤补给",
    combatPower: 3,
    appearance: "瘦高个子，穿深蓝制服，在前台桌子上撑下巴打盹。",
    taboo: "不要在他打盹时叫醒他。",
    defaultFavorability: 30,
    lore: "巡一圈会回来，灯光跟着他挪。午夜班只他一人。他不查证件——只问「你是几时来的」。",
  },
  {
    id: "N-026",
    name: "开关姐",
    location: "3F 走廊尽头",
    floor: "3",
    personality: "执拗",
    specialty: "情报提供",
    combatPower: 2,
    appearance: "抱塑料盆的女人，站在走廊尽头一直按墙上的开关。",
    taboo: "不要替她按开关。",
    defaultFavorability: 28,
    lore: "有时候开关按了，灯不亮。她不在乎——她只在乎「按」这个动作本身。",
  },
  {
    id: "N-027",
    name: "睡衣姐妹花",
    location: "6F 走廊",
    floor: "6",
    personality: "叨扰",
    specialty: "情报提供",
    combatPower: 3,
    appearance: "两个穿碎花睡衣的中年女人，端着方便面在走廊里小声说话。面型相像，但说话节奏一快一慢。",
    taboo: "不要问她们是双胞胎。",
    defaultFavorability: 32,
    lore: "她们只是住 6F 的普通住户，并非阿织/阿绣。她们怕被错认——若被问「是那两个小女孩吗」，会沉默走开。",
  },
  // ═══ v4 全楼层新增 16 条（N-028..N-043）═══
  {
    id: "N-028",
    name: "守夜老吴",
    location: "B2 配电室",
    floor: "B2",
    personality: "谨慎",
    specialty: "战斗辅助",
    combatPower: 7,
    appearance: "六十多岁，穿旧棉袄，腰上挂一串钥匙。他只在 B2 配电室外的长椅坐。",
    taboo: "不要向他借钥匙。",
    defaultFavorability: 40,
    lore: "他说他「只是守夜的」，但他知道 B2 几条暗道的走向。他从不亲自下去，只听回声判断下面是否还干净。",
  },
  {
    id: "N-029",
    name: "前台小周",
    location: "2F 前台",
    floor: "2",
    personality: "礼貌",
    specialty: "情报提供",
    combatPower: 3,
    appearance: "二十出头，戴半框眼镜，坐在 2F 前台桌后核对来访登记。",
    taboo: "不要翻他桌上的登记本。",
    defaultFavorability: 45,
    lore: "他负责登记 2F 楼层的访客与住户出入，但他从不让访客看登记本——「写了什么不重要」。",
  },
  {
    id: "N-030",
    name: "楼道张师傅",
    location: "4F 楼道",
    floor: "4",
    personality: "随和",
    specialty: "后勤补给",
    combatPower: 4,
    appearance: "五十多岁，手里总拎一只塑料桶，看见 4F 楼道地上有水渍会立刻蹲下擦。",
    taboo: "不要阻止他擦地。",
    defaultFavorability: 50,
    lore: "他说 4F 楼道「不能有积水」。没人知道为什么。他擦地时哼的是一首听不出年代的童谣。",
  },
  {
    id: "N-031",
    name: "老画室租户老谢",
    location: "5F_Studio503",
    floor: "5",
    personality: "寡言",
    specialty: "情报提供",
    combatPower: 5,
    appearance: "七十多岁，旧布衫，背微驼，眼窝深陷。他总站在 5F 画室门外，看里面出神。",
    taboo: "不要在他面前提起叶的画。",
    defaultFavorability: 35,
    lore: "他说他「以前也租过这间画室」，但物业档案里没有他的名字。叶见到他会避开。",
  },
  {
    id: "N-032",
    name: "走廊常驻老陈",
    location: "6F 走廊长椅",
    floor: "6",
    personality: "健忘",
    specialty: "情报提供",
    combatPower: 3,
    appearance: "六十多岁，穿褪色运动服，常坐在 6F 走廊长椅上看窗外。他会反复问「现在几号」。",
    taboo: "不要直接回答他的日期问题。",
    defaultFavorability: 38,
    lore: "他记得住每个人的名字，但记不住日期。他被时间错层影响过，现在反过来——他说「日子」是谎言，「人」是真的。",
  },
  {
    id: "N-033",
    name: "7F 老住户老吴",
    location: "7F 走廊尽头",
    floor: "7",
    personality: "沉默",
    specialty: "情报提供",
    combatPower: 6,
    appearance: "七十多岁，旧军装外套，腰背笔直。他总站在 7F 走廊尽头的窗户前。",
    taboo: "不要从他身后经过。",
    defaultFavorability: 40,
    lore: "他说他「守了 7F 三十年」。他从未解释他在守什么。住户传闻他是前住户中最久的，但他从不被记入名册。",
  },
  {
    id: "N-034",
    name: "7F 点灯阿珍",
    location: "7F 楼道拐角",
    floor: "7",
    personality: "虔诚",
    specialty: "后勤补给",
    combatPower: 5,
    appearance: "四十多岁，穿深色棉布衣裳，每晚固定时刻会点亮 7F 楼道所有廊灯。",
    taboo: "不要熄灭她刚点亮的灯。",
    defaultFavorability: 45,
    lore: "她相信 7F 楼道「不能全暗」。没人知道她是几时开始守这习惯的。她记得每一盏灯的位置。",
  },
  {
    id: "N-035",
    name: "大堂夜班咖啡小弟",
    location: "1F 大堂",
    floor: "1",
    personality: "机灵",
    specialty: "后勤补给",
    combatPower: 2,
    appearance: "二十出头，旧 T 恤，推一辆咖啡车，每晚 10 点到次日凌晨 1 点在 1F 大堂出摊。",
    taboo: "不要问他咖啡的来源。",
    defaultFavorability: 40,
    lore: "他的咖啡豆从来不出现在采购清单上。但每一杯都让熬夜的人更清醒。",
  },
  {
    id: "N-036",
    name: "访客登记员老秦",
    location: "1F_GuardRoom",
    floor: "1",
    personality: "刻板",
    specialty: "情报提供",
    combatPower: 4,
    appearance: "五十出头，半秃顶，戴老花镜，在 1F 保安室登记桌前核对访客证件。",
    taboo: "不要让他看到你的证件背面。",
    defaultFavorability: 38,
    lore: "他只翻证件正面，背面一律不看。住户传言他过去在「另一边」干过登记，但他从不应承。",
  },
  {
    id: "N-037",
    name: "2F 退休护理员方姨",
    location: "2F 走廊",
    floor: "2",
    personality: "温和",
    specialty: "后勤补给",
    combatPower: 4,
    appearance: "六十出头，旧护士服改的便装，腰间别着听诊器。她走路很慢，但总在 2F 走廊里巡视。",
    taboo: "不要让她替你量血压。",
    defaultFavorability: 50,
    lore: "她已退休十年，但她说「老毛病没退」。她从不主动给人看病——只在她觉得「该量」时叫住人。",
  },
  {
    id: "N-038",
    name: "3F 楼梯常住户阿芳",
    location: "3F 楼梯间",
    floor: "3",
    personality: "爽利",
    specialty: "情报提供",
    combatPower: 4,
    appearance: "四十出头，短发，背一只布包，总在 3F 楼梯间上上下下。她从不等电梯。",
    taboo: "不要问她「住几层」。",
    defaultFavorability: 42,
    lore: "她住 3F，但她从不坐电梯。她说「电梯里太静」。她能听出每层楼道是不是有「别的脚步声」。",
  },
  {
    id: "N-039",
    name: "4F 王老师",
    location: "4F 401 室",
    floor: "4",
    personality: "温和",
    specialty: "情报提供",
    combatPower: 5,
    appearance: "六十出头，旧中山装，戴老花镜。他与张先生（N-006）共住 4F 401 室，二人从不同时出现。",
    taboo: "不要让他跟张先生同时在场。",
    defaultFavorability: 40,
    lore: "他教过语文，张先生教过数学。他们共用同一扇门，但住户传言他们「错开日子」。他说他跟张先生「从未正式照面」。",
  },
  {
    id: "N-040",
    name: "5F 画室学生小林",
    location: "5F_Studio503",
    floor: "5",
    personality: "怯懦",
    specialty: "情报提供",
    combatPower: 3,
    appearance: "二十出头，旧围裙，手指总有洗不掉的颜料。她偶尔出现在 5F 画室角落。",
    taboo: "不要问她画的是什么。",
    defaultFavorability: 35,
    lore: "她自称是叶（N-007）的学生，但叶从未承认。她画的东西没人见过。她说「画了就会消失」。",
  },
  {
    id: "N-041",
    name: "6F 夜猫子小郑",
    location: "6F 楼道窗",
    floor: "6",
    personality: "孤僻",
    specialty: "情报提供",
    combatPower: 4,
    appearance: "三十出头，旧卫衣，戴耳机，总在 6F 楼道尽头的窗台边坐到凌晨。",
    taboo: "不要摘下他的耳机。",
    defaultFavorability: 32,
    lore: "他戴的耳机从不放音乐——他说「放别的会被听进去」。他只听「楼自己说话」。",
  },
  {
    id: "N-042",
    name: "7F 窗台老人老庄",
    location: "7F 走廊窗台",
    floor: "7",
    personality: "淡漠",
    specialty: "情报提供",
    combatPower: 5,
    appearance: "七十多岁，旧中山装，戴老花镜，手持一只空茶杯。他总在 7F 走廊窗台边坐。",
    taboo: "不要给他倒茶。",
    defaultFavorability: 30,
    lore: "他喝茶的杯子永远是空的。他从不向人讨茶，也不接受人倒的茶。他只「闻」茶香。",
  },
  {
    id: "N-043",
    name: "B1 锅炉工老钱",
    location: "B1_BoilerRoom",
    floor: "B1",
    personality: "沉默",
    specialty: "后勤补给",
    combatPower: 6,
    appearance: "五十出头，旧工装，脸被炉火烤得发红。他总在 B1 锅炉房外面蹲着抽烟。",
    taboo: "不要让他在炉前停下手。",
    defaultFavorability: 45,
    lore: "他说锅炉「不能停」。没人知道炉里烧的是什么——但他说「停下就凉了，凉了就会有人哭」。",
  },
  {
    id: "N-044",
    name: "廖暗",
    location: "3F_Room301",
    floor: "3",
    personality: "沉静、警觉、务实",
    specialty: "异常模式观察与逃生路线",
    combatPower: 12,
    appearance: "三十出头，深色外套领口立起，眼神总在扫过门框与墙角。手里常捏着一截粉笔，用来在地板上画动线。",
    taboo: "不要追问他为什么总能在异常发生前半步到场。",
    defaultFavorability: 40,
    lore: "廖暗是公寓里少数把异常当可研究对象的人。他不记得自己何时入住——只记得某次月初误入后再也没找到出口。他用粉笔在每层墙角画动线图，记录异常出现的时间、地点、频率，靠这套手账活到现在。他知道几条不在登记图上的隐藏通道，但从不对人完整说出路线，只一句一句地喂。他与麟泽、欣蓝、老刘各有职能上的擦肩，却从不解释自己为什么信任他们。他不是七辅锚之一——辅锚系统有它自己的位号，廖暗只是个活得够久的旁观者。",
  },
  {
    id: "N-045",
    name: "苏弥",
    location: "6F_Room601",
    floor: "6",
    personality: "温柔、敏感、共情",
    specialty: "情绪缓冲与记忆收容",
    combatPower: 6,
    appearance: "二十八九岁，常穿宽大的旧针织衫，袖口磨白。说话时习惯微微侧头，像在听更远处的什么。",
    taboo: "不要把她收集的「别人的记忆」碎片强行还回去——她靠收容它们维持自身平衡。",
    defaultFavorability: 50,
    lore: "苏弥住在 6F 601，紧挨着章嫂与阿织阿绣那一摊情绪高频区。她收集别人不要的碎片记忆——某住户遗忘的童年、某人丢掉的执念——像在替公寓做一部分情绪缓冲。她相信大多数「异常」只是受了伤，但这让她在 6F 的镜像污染里格外脆弱。她知道哪些反光面会让住户「不高兴」，也知道自己某天可能变成她安抚过的那种东西。她不是辅锚——她只是个把别人不要的痛接住的人。",
  },
];

export const NPCS: readonly NPC[] = applyNpcProfileOverrides(NPCS_BASE);
