// src/lib/registry/rules.ts
// 如月公寓生存笔记：残页、传闻、住户经验与物业口径混杂，不再作为绝对规则。

import { REVEAL_TIER_RANK } from "./revealTierRank";
import type { ApartmentSurvivalNote } from "./types";

export const APARTMENT_SURVIVAL_NOTES: readonly ApartmentSurvivalNote[] = [
  {
    id: "note_red_water_settle",
    title: "红水静置",
    surfaceText: "入住须知残页：自来水若呈红色，不要直接饮用；先静置，看沉淀是否下坠。",
    source: "入住须知残页",
    reliability: "partly_true",
    knownToPlayerByDefault: false,
    validWhen: "红水来自普通管线渗漏或低强度沉淀物时，静置能降低污染活性。",
    invalidWhen: "水源已被管道凝聚体标记，或地漏/马桶同时返红时，静置不再安全。",
    actualMechanism: "红水是管道分拣的表层表现；静置只是在短时间内让活性沉淀物下坠，不是净化。",
    revealTier: REVEAL_TIER_RANK.surface,
    relatedAnomalyIds: ["A-004"],
    relatedLocationIds: ["2F_Clinic201", "2F_Corridor", "B1_Laundry"],
  },
  {
    id: "note_mirror_cover",
    title: "遮镜经验",
    surfaceText: "住户传言：凌晨后把镜子遮住；如果倒影慢半拍，别和它对视。",
    source: "住户传言",
    reliability: "partly_true",
    knownToPlayerByDefault: false,
    validWhen: "镜像错位处于低强度观察期，遮挡与闭眼能中断视觉定位。",
    invalidWhen: "镜面已成为通道或倒行者已完成定位时，遮挡只能争取撤离时间。",
    actualMechanism: "镜像/方向异常通过视线建立映射；遮镜不是禁忌，而是切断传感面。",
    revealTier: REVEAL_TIER_RANK.surface,
    relatedAnomalyIds: ["A-006"],
    relatedLocationIds: ["6F_Stairwell", "6F_Room601", "5F_Studio503"],
  },
  {
    id: "note_dog_bark",
    title: "别回应狗叫",
    surfaceText: "前人笔记：4 楼尽头有狗叫时，不要敲门，不要回话，也别替任何人去找狗。",
    source: "前人笔记",
    reliability: "true",
    knownToPlayerByDefault: false,
    validWhen: "声音诱饵尚未锁定具体步频和方向时，静默撤离最有效。",
    invalidWhen: "已主动回应、奔跑或制造连续声源后，需要诱饵/隔音/关系协助才能脱身。",
    actualMechanism: "无头猎犬沿声源与情绪反应追踪；狗叫是声带诱捕，不是求救。",
    revealTier: REVEAL_TIER_RANK.surface,
    relatedAnomalyIds: ["A-002"],
    relatedLocationIds: ["4F_CorridorEnd", "4F_Room401", "4F_Room402"],
  },
  {
    id: "note_wall_swallow",
    title: "墙内吞咽声",
    surfaceText: "住户经验：墙里有吞咽声时别敲墙回应，先离开潮湿或发热的墙面。",
    source: "住户经验",
    reliability: "partly_true",
    knownToPlayerByDefault: false,
    validWhen: "楼体只在进行低强度分拣，远离墙面能降低被标记概率。",
    invalidWhen: "墙面已显眼、发热或出现肉膜时，单纯安静不足以撤离。",
    actualMechanism: "墙体吞咽是空间消化秩序的表层声响；回应会让墙面获得更清晰的定位样本。",
    revealTier: REVEAL_TIER_RANK.fracture,
    relatedAnomalyIds: ["A-005", "A-004"],
    relatedLocationIds: ["5F_Room501", "5F_Studio503", "2F_Corridor"],
  },
  {
    id: "note_thirteenth_floor",
    title: "十三楼错层",
    surfaceText: "物业残页：本楼没有真实 13 层；看见 13 楼按钮或门牌时，先折返，不要把它当新楼层。",
    source: "物业残页",
    reliability: "true",
    knownToPlayerByDefault: false,
    validWhen: "13 楼仍是错层诱导或未消化层投影，及时折返能脱离牵引。",
    invalidWhen: "已经跨入门内并回应呼唤后，需要锚点/关系/代价窗口协助。",
    actualMechanism: "13 楼是未消化层投影，不是地图新增楼层；它利用出口想象制造假门。",
    revealTier: REVEAL_TIER_RANK.fracture,
    relatedAnomalyIds: ["A-007"],
    relatedLocationIds: ["7F_SealedDoor", "7F_Bench"],
  },
  {
    id: "note_red_uniform_tea",
    title: "红制服茶水",
    surfaceText: "住户传言：午夜后遇见红制服保洁员递茶，可以礼貌拒绝，不要接杯子。",
    source: "住户传言",
    reliability: "true",
    knownToPlayerByDefault: false,
    validWhen: "保洁员仍在执行分发流程，礼貌拒绝能避免被纳入当次配额。",
    invalidWhen: "已接杯或被标记为缺水目标时，需要净化/交易/替代容器转移风险。",
    actualMechanism: "所谓茶水是管线沉淀物的分发节点；拒绝不是礼仪禁忌，而是避开账本记录。",
    revealTier: REVEAL_TIER_RANK.surface,
    relatedAnomalyIds: ["A-004"],
    relatedLocationIds: ["B1_Laundry", "2F_Corridor", "4F_CorridorEnd"],
  },
  {
    id: "note_basement_open",
    title: "地下室夜门",
    surfaceText: "旧告示：地下室夜里开门时，不要把它当捷径；那通常是未消化区在呼吸。",
    source: "旧告示",
    reliability: "partly_true",
    knownToPlayerByDefault: false,
    validWhen: "异常门缝只连向普通未消化区时，远离能避免被拖入。",
    invalidWhen: "B2 通行权限、钥物与代价链已成立时，受控进入不等于误闯。",
    actualMechanism: "B1 与 B2 相邻但不是普通通道；夜门可能是回收口，真正通行权来自出口主线链。",
    revealTier: REVEAL_TIER_RANK.fracture,
    relatedAnomalyIds: ["A-008"],
    relatedLocationIds: ["B1_SafeZone", "B2_Passage"],
  },
  {
    id: "note_rot_door",
    title: "腐肉味房门",
    surfaceText: "前人笔记：腐肉味从紧闭房门里冒出来时，不要窥探，先记下门牌再离开。",
    source: "前人笔记",
    reliability: "partly_true",
    knownToPlayerByDefault: false,
    validWhen: "门内只是消化残留或拟态墙试探，记录门牌比开门更安全。",
    invalidWhen: "任务或救援目标已在门内，需要反制物/关系协助/撤退路线，而不是盲目回避。",
    actualMechanism: "气味是空间在筛选好奇心与救援冲动；门后不总是怪物，也可能是被污染的线索。",
    revealTier: REVEAL_TIER_RANK.surface,
    relatedAnomalyIds: ["A-005", "A-007"],
    relatedLocationIds: ["5F_Room501", "7F_SealedDoor"],
  },
  {
    id: "note_mechanical_watch",
    title: "机械表校时",
    surfaceText: "物业残页：楼内时钟会互相打架；先保留自己的机械表或电子表作参照。",
    source: "物业残页",
    reliability: "true",
    knownToPlayerByDefault: false,
    validWhen: "时间错位尚未覆盖个人锚点时，随身计时器能帮助确认行动顺序。",
    invalidWhen: "表盘停走或显示未来日期时，它本身也已被纳入异常。",
    actualMechanism: "时钟并非神秘禁忌，而是身份登记和时间分拣的外显接口。",
    revealTier: REVEAL_TIER_RANK.surface,
    relatedAnomalyIds: ["A-001"],
    relatedLocationIds: ["1F_Lobby", "1F_PropertyOffice", "4F_Room401"],
  },
  {
    id: "note_reverse_stair",
    title: "倒行楼梯",
    surfaceText: "住户经验：楼梯间有人背对你倒着下行时，别抢在它身后超过；先闭眼扶墙等一会儿。",
    source: "住户经验",
    reliability: "true",
    knownToPlayerByDefault: false,
    validWhen: "倒行者仍在慢速巡段，闭眼和扶墙能减少方向映射。",
    invalidWhen: "已与镜面后脑建立视觉接触，或在楼梯上奔跑时，需要外物/同伴制造撤退窗口。",
    actualMechanism: "倒行者利用视觉与方向感建立反向映射；闭眼是断开定位，不是宗教仪式。",
    revealTier: REVEAL_TIER_RANK.surface,
    relatedAnomalyIds: ["A-006"],
    relatedLocationIds: ["6F_Stairwell"],
  },
];

/** @deprecated 旧调用只需要表层文本；请优先使用 APARTMENT_SURVIVAL_NOTES。 */
export const APARTMENT_RULES: readonly string[] = APARTMENT_SURVIVAL_NOTES.map((note) => note.surfaceText);
