export type AdminMetricScope = "all" | "registered" | "guest";
export type AdminMetricDefinition = {
  id: string;
  nameZh: string;
  meaning: string;
  calculation: string;
  source: string;
  refresh: string;
  scope: AdminMetricScope;
  degradable: boolean;
  notes: string;
};

export const ADMIN_METRIC_DEFINITIONS: AdminMetricDefinition[] = [
  {
    id: "overview.new_registered_today",
    nameZh: "今日新增注册用户",
    meaning: "今天首次完成账号注册的用户数。",
    calculation: "analytics_events 中 user_registered 去重 user_id。",
    source: "analytics_events.event_name=user_registered / admin_metrics_daily.new_users",
    refresh: "写入实时增量；cron 可按日重建",
    scope: "registered",
    degradable: true,
    notes: "DB 不可用时返回 0 并标记 degraded。",
  },
  {
    id: "overview.new_guests_today",
    nameZh: "今日新增游客",
    meaning: "今天首次出现的游客设备/浏览器身份数。",
    calculation: "guest_registry.first_seen_at 落在今日。",
    source: "guest_registry",
    refresh: "实时写入",
    scope: "guest",
    degradable: true,
    notes: "游客清理本地数据会被视为新游客。",
  },
  {
    id: "overview.active_actors_today",
    nameZh: "今日活跃账号/游客",
    meaning: "今天发生有效行为的登录用户与游客合计。",
    calculation: "按账号或游客身份去重统计今日有效活跃。",
    source: "每日活跃记录",
    refresh: "chat / heartbeat / cron",
    scope: "all",
    degradable: true,
    notes: "包含游客与注册用户，适合看真实流量。",
  },
  {
    id: "overview.ai_success_rate_today",
    nameZh: "今日 AI 成功率",
    meaning: "AI 回合请求成功完成的比例。",
    calculation: "chat_request_finished payload.success=true / all chat_request_finished。",
    source: "analytics_events.payload",
    refresh: "每次 /api/chat 完成后异步写入",
    scope: "all",
    degradable: true,
    notes: "keys_missing 降级也会进入失败/降级分析。",
  },
  {
    id: "overview.ai_failure_rate_today",
    nameZh: "今日 AI 失败率",
    meaning: "AI 回合请求失败或未正常完成的比例。",
    calculation: "chat_request_finished payload.success=false / all chat_request_finished。",
    source: "analytics_events.payload",
    refresh: "每次 /api/chat 完成后异步写入",
    scope: "all",
    degradable: true,
    notes: "用于判断等待、模型、JSON 收口或网关故障。",
  },
  {
    id: "overview.token_cost_today",
    nameZh: "今日 AI 用量",
    meaning: "今天 AI 主链路消耗的用量总和。",
    calculation: "今日 AI 回合记录的用量求和。",
    source: "analytics_events.token_cost",
    refresh: "实时查询 / cron 日聚合",
    scope: "all",
    degradable: true,
    notes: "字段缺失时按 0 处理。",
  },
  {
    id: "overview.online_registered_current",
    nameZh: "当前在线注册用户",
    meaning: "当前仍在近窗口内活跃的注册用户数。",
    calculation: "presence / user_sessions 近窗口在线用户计数。",
    source: "presence / user_sessions",
    refresh: "页面刷新时实时查询",
    scope: "registered",
    degradable: true,
    notes: "Redis/DB 不可用时降级。",
  },
  {
    id: "overview.online_guests_current",
    nameZh: "当前在线游客",
    meaning: "当前仍在近窗口内活跃的游客数。",
    calculation: "presence / analytics_events 近窗口游客计数。",
    source: "presence / analytics_events",
    refresh: "页面刷新时实时查询",
    scope: "guest",
    degradable: true,
    notes: "游客身份清理会影响估算。",
  },
  {
    id: "journey.home_viewed",
    nameZh: "首页曝光",
    meaning: "玩家到达首页的人数。",
    calculation: "analytics_events event_name=home_viewed distinct actor。",
    source: "analytics_events",
    refresh: "客户端打开首页后异步写入",
    scope: "all",
    degradable: true,
    notes: "用于漏斗起点。",
  },
  {
    id: "ai.ttft_p50",
    nameZh: "首段等待中位数",
    meaning: "50% AI 回合首个可见 token/片段等待时长。",
    calculation: "按 AI 回合完成事件中的首段等待时长计算中位数。",
    source: "analytics_events.payload / chat_request_finished",
    refresh: "每次 /api/chat 完成后异步写入",
    scope: "all",
    degradable: true,
    notes: "用于观察典型等待体验。",
  },
  {
    id: "ai.ttft_p95",
    nameZh: "首段等待 95 分位",
    meaning: "95% AI 回合首个可见 token/片段等待时长。",
    calculation: "按 AI 回合完成事件中的首段等待时长计算 95 分位。",
    source: "analytics_events.payload / chat_request_finished",
    refresh: "每次 /api/chat 完成后异步写入",
    scope: "all",
    degradable: true,
    notes: "如果模型未流出正文则样本会缺失。",
  },
  {
    id: "ai.total_latency_p50",
    nameZh: "总耗时中位数",
    meaning: "50% AI 回合从提交到终帧完成的时长。",
    calculation: "按 AI 回合完成事件中的总耗时计算中位数。",
    source: "analytics_events.payload / chat_request_finished",
    refresh: "每次 /api/chat 完成后异步写入",
    scope: "all",
    degradable: true,
    notes: "用于观察典型完整回合时长。",
  },
  {
    id: "ai.total_latency_p95",
    nameZh: "总耗时 95 分位",
    meaning: "95% AI 回合从提交到终帧完成的时长。",
    calculation: "按 AI 回合完成事件中的总耗时计算 95 分位。",
    source: "analytics_events.payload / chat_request_finished",
    refresh: "每次 /api/chat 完成后异步写入",
    scope: "all",
    degradable: true,
    notes: "包含 final hooks 与终帧前收口。",
  },
  {
    id: "content.validator_issues",
    nameZh: "叙事规则冲突",
    meaning: "叙事校验器发现的问题数。",
    calculation: "叙事校验事件中记录的问题数量求和。",
    source: "叙事校验事件",
    refresh: "每次有 validator issue 时异步写入",
    scope: "all",
    degradable: true,
    notes: "用于定位世界知识、NPC 认知和规则冲突。",
  },
  {
    id: "health.db",
    nameZh: "DB 可用性",
    meaning: "后台查询依赖的 PostgreSQL 当前是否可用。",
    calculation: "SELECT 1 ping。",
    source: "PostgreSQL",
    refresh: "页面刷新时检测",
    scope: "all",
    degradable: true,
    notes: "不可用时后台应返回 degraded，不影响前台主流程。",
  },
];

export function getAdminMetricDefinition(id: string): AdminMetricDefinition | null {
  return ADMIN_METRIC_DEFINITIONS.find((m) => m.id === id) ?? null;
}
