name: Sync to Gitee

on:
  push:
    branches:
      - main  # 触发分支为 main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repo to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/bei666qi-pan
          dst: gitee/bei-qi-luo
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "VerseCraft"
          force_update: true
          debug: true
          clone_style: "ssh"
